package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb
* cf126cd packaging
* bcf68ff selecting needed yast packages for the second stage correctly
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_141230_bug_909751'

package/autoyast2.changes, src/clients/inst_autosetup.rb, src/clients/inst_autosetup_upgrade.rb
Do not merge before SP1 development starts
=> For SLE12-SP1: load release notes of extensions also during AutoYaST (bnc#893586)

src/modules/AutoinstClass.rb, test/AutoinstClass_test.rb, test/fixtures/classes/classes.xml, test/fixtures/classes/swap/largeswap.xml, test/fixtures/classes/swap/largeswap_noroot.xml, test/fixtures/etc/autoinstall/classes.xml
Hi all,
I've been doing some refactoring work on AutoinstClass module. I'd like to refactor the whole class but, given that I have no prior experience in developing Yast, I think that it's time to get some feedback.
Thank you in advance.
Regards,
Imobach
=> AutointClass refactoring

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
New autoinst flag in general/mode section: final_restart_services.
Restarting all services after finishing the installation.
The default is "true".
=> Bug 923992

README.md
- I've added the generic stuff
- And also specific stuff for testing AutoYast (as I've got it from @schubi2 )
=> Updated README.md according to the Yast template

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
* 3bf4a90 packaging
* b9885d9 added new autoyast flag: activate_systemd_default_target
* 5ed82c6 Merge pull request #108 from kobliha/docu_for_testing
* 43eb756 Added generic docu stuff
* 34841b0 Updated documentation - Testing
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150410_bug_923992'

test/AutoInstallRules_test.rb, test/AutoinstClass_test.rb, test/test_helper.rb
Fix the tests in i586. BTW, a test/test_helper.rb file was added to avoid code duplication in tests initialization.
=> Fix AutoInstallRules tests

test/AutoinstClass_test.rb
It must avoid a flickering test on for AutoinstClassClass.
=> Avoid flickering tests for AutoinstClassClass

package/autoyast2.changes, package/autoyast2.spec
=> Added libxslt into BuildRequires - needed for running test-cases

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/xml.rb
* 3c28488 fixed rubygem
* b6cf968 packaging
* a166ffe added new tag restricts for ntp configuration
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150511_restrict_tag'

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb, src/modules/Y2ModuleConfig.rb, test/Y2ModuleConfig_test.rb, test/fixtures/desktop_files/desktops.yml
* fa1019d packaging
* 1f47e09 fixed testcases
* eafb814 added users
* 6d5eba1 checking autoyast merge entry; checking for corresponding *_auto.rb
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150512_reporting_unsupported_modules'

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb, test/Y2ModuleConfig_test.rb, test/fixtures/profiles/unhandled_and_obsolete.xml
* 8848fda packaging
* 15b7fc1 added -upgrade- to GENERIC_PROFILE_SECTIONS
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150701_bnc_935915'

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc, src/modules/AutoinstGeneral.rb, test/AutoinstGeneral_test.rb, test/fixtures/profiles/general_with_time_sync.xml, test/fixtures/profiles/general_without_time_sync.xml
* 3436c2b packaging
* 1f1da44 syncing hardware time via ntp before starting the installation
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150710_ntp_syncing_before_starting_installation'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb, test/fixtures/profiles/software.xml
* 2d1da31 packaging
* 0bdc3ca install packages only if the have not already been installed
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150731_must_not_reinstall_packages'

package/autoyast2.changes, package/autoyast2.spec, src/clients/autoinst_scripts2_finish.rb, src/clients/inst_autoconfigure.rb
* cd1006b packaging
* f532f58 Creating init scripts in for the autoyast-initscripts.service in the first installation stage
I will write an integration test for the update too.......
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150807_writing_init_scripts_in_first_installation_stage'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstStorage.rb
I will add an integration test too......
* 023c5a6 packaging
* 91b5311 typo
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150811_typo_in_partitioning'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstConfig.rb, src/modules/AutoinstGeneral.rb
* 3b5ba6b packaging
* 306dd05 added new flag for cio_ignore in autoyast
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150813_cio_ignore'

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/xml.rb
The only missing commit is [added tag "restricts"](https://github.com/yast/yast-autoinstallation/commit/cdc96b7008d2786992e059aad7b3d2e068c2db63).
=> Merge SLES-12-GA into SLE-12-GA

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
* d785a95 packaging
* 54055b0 do not restart dbus
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150825_no_restart_dbus'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
Do not restart dbus service after the installation has been finished
=> Sle 12 ga bug 937900

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb
* 5154f4c packaging
* 732560c setting network in first installation workflow
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_150918_writing_network_settings_in_first_stage'

package/autoyast2.changes, package/autoyast2.spec, src/Makefile.am, src/lib/autoinstall/pkg_gpg_check_handler.rb, src/modules/AutoInstall.rb, src/modules/AutoinstGeneral.rb, test/AutoInstallRules_test.rb, test/AutoInstall_test.rb, test/Makefile.am, test/lib/pkg_gpg_check_handler_spec.rb, test/lib/pkg_gpg_check_handler_test.rb, test/test_helper.rb
Together with https://github.com/yast/yast-pkg-bindings/pull/52 should solve bsc#948608.
=> SLE 12: handle pkgGpgCheck callback

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb
Fixes the urgent part of the bug.
=> Added more sections to Profile::GENERIC_PROFILE_SECTIONS (bnc#950294)

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb
* 15bb812 packaging
* 3212886 do not report missing packages
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_151021_cloning_software'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
NOTE: I will create an integration test for....
* 2f87a7f packaging
* 01268cb ignore restarting wickedd* services
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_151022_ignore_restart_wickedd'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstGeneral.rb, test/AutoinstGeneral_test.rb
* cf09195 packaging
* f3a103d using ntpdate instead of sntp for time syncing
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_151106_time_syncing'

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/autoyast-rnc/software.rnc
Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for this module.
=> Fix AutoYaST schema in SLE 12 GA

package/autoyast2.changes, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/autoyast-rnc/scripts.rnc, src/autoyast-rnc/software.rnc
Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for SLE 12 SP1.
=> Fix validation of AutoYaST profiles

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb, test/Y2ModuleConfig_test.rb, test/fixtures/profiles/unhandled_and_obsolete.xml
Added "cobber" to the obsolete profile section.
=> Bnc 955878

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/autoyast-rnc/scripts.rnc, src/autoyast-rnc/software.rnc
Merge `sle-12-sp1-after_release` in SP1 branch.
=>  Merge post SLE 12 SP1 release changes

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
Reducing loglevel Error->Warning for obsolte YAST modules.
=> Bnc 955878 2

package/autoyast2.changes, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/autoyast-rnc/scripts.rnc, src/autoyast-rnc/software.rnc
Merge `SLE-12-SP1` branch into `master`.
=> Merge SLE 12 SP1 into master

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstScripts.rb
fix for broken init scripts which have been defined inside of a autoyast configuration file
=> Bnc 961320 2

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb, src/modules/AutoinstScripts.rb
* dcaa61f packaging
* 42d6f4f Merge pull request #180 from yast/bnc_961320_2
* ccb094a taking scriptPath
* acd3693 packaging
* 1fb071a fixed included init scripts
* 65979a0 Merge pull request #178 from yast/bnc_955878_2
* 08c5313 typo
* 10946d8 packaging
* ac512c3 reduced log level for obsolete modules
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160114_init_scripts_2'

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/io.rb
Installation with "autoyast=default". Fixed nil exception error.
=> Bnc 959723

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/io.rb
* 56a9a2a merged with SP1
* 140a89a Merge pull request #182 from yast/bnc_959723
* a8c1d01 packaging
* c0140ee fixed nil.empty?
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160115_bug_959723'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstallRules.rb, src/modules/Profile.rb, test/AutoInstallRules_test.rb
* 2409429 merged with SLES12-SP1
* 135f62f packaging
* eef6e83 fix in -or- rules operator
* e63fc7e Merge pull request #184 from imobach/fix-init-section
* c7384be Improve changelog message
* 5ed4d98 Bump version and update changes file
* f67308f Add 'init' section to generic AutoYaST sections
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160119_master_merged_with_sles12_sp1'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstGeneral.rb, test/AutoinstGeneral_test.rb
Adapting sntp call to new API (version 4.2.8).
=> Bnc 960059

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstLVM.rb
AutoYaST NilClass nil in SWIG method 'createLvmLv'
=> Bnc 962238

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstLVM.rb
* fa6b00d adapt version
* faf6f31 Merge pull request #188 from yast/bnc_962238
* e478ee7 packaging
* 5c529d8 auto setting in LVM partitioning
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160121_bug_962034_master'

package/autoyast2.changes, src/clients/ayast_probe.rb, src/modules/AutoInstallRules.rb, test/AutoInstallRules_test.rb
* It's not applicable to SLE 12 (it doesn't work since SLE 11).
=> Remove haspcmcia rule

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/io.rb
This is a backport from SLES12-SP1 and master
=> Installation with autoyast=default. Fixed nil exception error.

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb
* 79adbab packaging
* bad326f confirming base license
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160211_autoyast_confirm_licences'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
Port fix from #197. BTW, it also merges `SLE-12-GA` branch into SP1.
=> Fix waiting services SLE 12 SP1

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
Port of #198. BTW, I'm merging `SLE-12-SP1` branch into `master`. `inst_autoconfigure` deserves some refactoring, but I'll try to do it after the sprint.
=> Fix waiting services

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstallRules.rb, test/AutoInstallRules_test.rb, test/fixtures/network/wicked.out, test/fixtures/network/wicked_partial.out
This PR merges changes from SLE-12-GA into SP1. The intention is to get the fix for [bsc#963137](https://bugzilla.suse.com/show_bug.cgi?id=963137).
=> Fix install rules SLE 12 SP1

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstallRules.rb, test/AutoInstallRules_test.rb, test/fixtures/network/wicked.out, test/fixtures/network/wicked_partial.out, test/fixtures/output/ip_route.out
It was intended to be a merge of #201. But additionally I did some additional changes:
* Remove of bogus IP address (192.168.1.*).
* Use iproute2 tools instead of wicked.
IIRC, only the last commit was not reviewed.
=> Fix install rules in master

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb, src/clients/inst_autosetup_upgrade.rb
to be merged once https://github.com/yast/yast-network/pull/393 is submitted. Also add/update (yast2-network) version dependency into spec
=> Dropped references to LanUdevAuto

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc
This is related to https://github.com/yast/yast-installation/pull/362.
=> Added self update URL into the schema (FATE#319716)

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup_upgrade.rb
Screenshot is here
https://trello.com/c/umS5af4f/509-3-sle-12-sp2-p6b-m-media-based-autoupgrade-case-for-feature-320199-no-recommends-in-release-rpms
=> No Recommends in *-release RPMs

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb
* f06dd4f packaging
* 2e0df1b reset selection
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160518_glibc_bug'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb, src/clients/inst_autoinit.rb
* 3b90e35 reducing log level
* 406efa6 packaging
* 080f2ca moved reporting unsupported sections to first stage
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160519_bnc_955878'

package/autoyast2.changes, package/autoyast2.spec, src/Makefile.am, src/autoyast-rnc/ssh-import.rnc, src/clients/inst_autosetup.rb, src/modules/Profile.rb
* 8359beb packaging
* b9351b9 save settings
* 864d2d3 own call of import ssh_import
* 089d1e6 removing entry from profile
* 4d39241 fixed pathes
* b01dbfe adding ssh_import
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160524_ssh_import_support'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb
* 4d0571c packaging
* 4495609 typo
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160620_report_unsupported_modules'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoconfigure.rb
Fixes [bsc#984146](https://bugzilla.suse.com/show_bug.cgi?id=984146). The main part is done in https://github.com/yast/yast-network/pull/411.
(Internal tracking: https://trello.com/c/Q9ulwr8Q)
=> Set keep_install_network to 'true'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb
* c1f0648 packaging
* 0360c17 Updating new URI in /etc/install.inf (bnc#963487)
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160706_update_install_inf'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb, src/modules/AutoinstGeneral.rb
* 07d4d65 packaging
* 6089c90 set kexec_reboot correctly
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160531_kexec_reboot'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstDrive.rb, src/modules/AutoinstPartPlan.rb, test/AutoinstPartPlan_test.rb, test/fixtures/storage/nfs_root.yml
This is a backport of SP1 only:
https://github.com/yast/yast-autoinstallation/pull/225/files
* ddf0de5 merged bnc_986124_sles12_sp1
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160715_bnc_986124_sles12_sp2'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb
* 5bce3aa merged bug_990494_sle12_sp1
* 21dba6b added install_recommended flag
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160802_bug_990494_sle12_sp2'

POTFILES, src/include/autoinstall/ask.rb
related to https://trello.com/c/hyKEyicF/629-3-generate-and-submit-new-pot-files
=> Potfiles fix

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstPartPlan.rb, test/AutoinstPartPlan_test.rb, test/fixtures/storage/target_clone.yml
Please do not merge. This will be currently tested if it is working at all :-)
=> ignoring not needed devices

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb, src/clients/report_auto.rb
This PR also belongs to https://github.com/yast/yast-yast2/pull/492
=> Setting timeout for error popups has not been possible

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstallRules.rb, test/fixtures/output/ip_route.out
Fixes [bnc#997548](https://bugzilla.suse.com/show_bug.cgi?id=997548).
=> Fix IP detection in AutoYaST rules (SLE 12 SP2)

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstallRules.rb, test/fixtures/output/ip_route.out
=> Fix install rules master (take 2)

package/autoyast2.changes, package/autoyast2.spec, src/Makefile.am, src/desktop/clone_system.desktop
* 6dcb502 adding clone_system desktop file
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160930_desktop_clone_system'

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/clients/inst_autoinit.rb, src/include/autoinstall/autopart.rb, src/modules/AutoinstGeneral.rb, src/modules/AutoinstPartPlan.rb, src/modules/AutoinstPartition.rb, test/AutoinstGeneral_test.rb, test/AutoinstPartPlan_test.rb, test/Makefile.am, test/fixtures/storage/subvolumes.yml, test/include/autopart_test.rb, test/test_helper.rb
Merge SLE-12-SP2 branch into master in order to get #252.
=> Btrfs subvolume opts master

.travis.yml
=> Merge SLE 12 SP2 into master

package/autoyast2.changes, package/autoyast2.spec, src/bin/fetch_image.sh
* f0386f5 do not check certificate
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_161116_checking_images'

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb, src/modules/Y2ModuleConfig.rb, test/AutoinstGeneral_test.rb, test/Y2ModuleConfig_test.rb, test/profile_test.rb
=> Merge clone hidden

test/Y2ModuleConfig_test.rb, test/fixtures/desktop_files/desktops.yml
It should fix Jenkins tests: https://ci.suse.de/view/YaST/job/yast-autoinstallation-master/74/console.
=> Fix Y2ModuleConfig test

test/Y2ModuleConfig_test.rb, test/fixtures/desktop_files/desktops.yml
=> Merge fix y2module config test

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb, test/profile_test.rb
Fix an stupid bug related to #259.
=> Fix aliased resources merge

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb, test/profile_test.rb
=> Master fix aliased resources merge

.travis.yml, package/autoyast2.changes, package/autoyast2.spec, test/AutoinstPartPlan_test.rb
Fix https://bugzilla.suse.com/show_bug.cgi?id=1011489. See https://build.suse.de/package/live_build_log/Devel:CASP:1.0/autoyast2/standard/s390x by default.
=> Fix s390x build

Rakefile, package/autoyast2.changes, package/autoyast2.spec, test/AutoinstPartPlan_test.rb
This should fix building for SLE 12 SP3 in s390x.
=> Merge SLE 12 SP2 CASP into master

package/autoyast2.changes, package/autoyast2.spec, test/AutoinstPartPlan_test.rb
Port of #265 for `SLE-12-SP2`.
=> Fix building in s390x

package/autoyast2.changes, package/autoyast2.spec, src/Makefile.am, src/desktop/clone_system.desktop, src/modules/AutoinstStorage.rb, src/modules/Profile.rb, src/modules/Y2ModuleConfig.rb, test/AutoinstGeneral_test.rb, test/Y2ModuleConfig_test.rb, test/fixtures/desktop_files/desktops.yml, test/profile_test.rb
Merge changes from SLE 12 SP2 into CASP. Fix some bugs: bsc#985621, bsc#1012328, bsc#887115, bsc#1008301.
=> Merge SLE 12 SP2 into CASP

package/autoyast2.spec
=> Added missing Release field

package/autoyast2.changes
=> Fix changelog

package/autoyast2.changes, package/autoyast2.spec, src/clients/autoinst_scripts2_finish.rb, src/clients/inst_autoconfigure.rb, src/clients/inst_autopost.rb, src/modules/AutoinstScripts.rb, src/modules/AutoinstStorage.rb
* 1a2a5e3 merged with sles12-sp2
* cb25889 Merge pull request #274 from yast/SLE-12-SP2-bnc-1014859
* c8e974d moved post-script download to first stage
* 7378b91 Merge pull request #268 from yast/create-default-subvolumes
* 945c0e6 Add bug number to changes file
* 1675d68 Bump version and update changes file
* ba09e7d Create default subvolumes when they are not specified
* 9c0fd57 Merge pull request #267 from yast/fix-tests
* c25a767 Fix building in s390x
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_161214_merged_with_sles12_sp2'

.travis.yml, Dockerfile, package/autoyast2.changes, package/autoyast2.spec, test/AutoinstPartPlan_test.rb, test/profile_test.rb, test/test_helper.rb
- Also switch to Docker at Travis
=> Build fix for the latest core/ruby-bindings, use Docker at Travis

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb
Merges #273 into `master` branch.
=> Add minimalistic libzypp config master

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc
See https://github.com/yast/yast-installation/pull/501 for more details.
=> Add self_update element to the profile

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstDrive.rb, src/modules/AutoinstPartPlan.rb, test/AutoinstPartPlan_test.rb, test/fixtures/storage/nfs_root.yml
Merged from https://github.com/yast/yast-autoinstallation/pull/225
=> merged PR 225 from SP1

package/autoyast2.changes, package/autoyast2.spec
Change package dependency of yast2-update.
=> yast2-update dependency 

doc/network_scenarios.md
Trello: https://trello.com/c/ch6FlFxZ/835-3-sles12-sp2-autoyast-flag-keep-install-network
=> Added documentation explanining different network scenarios

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup_upgrade.rb
* 72fa13c merged with sles12-sp2
* ab2d62f Merge pull request #290 from yast/SLE-12-SP2_bnc_1014861
* 203c015 automatic product selektion moved to packager
* c95adc8 Merge pull request #276 from yast/SLE-12-SP2-bnc-1014859_2
* 9ffb81b typo
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_170308_bnc_1014861'

.travis.yml, package/autoyast2.changes, package/autoyast2.spec, test/AutoinstPartPlan_test.rb
bnc#1026027
it is time for this one, once the last of preceding PRs is merged (https://github.com/yast/yast-scanner/pull/11)
=> Removed dependency on insserv

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb
* a3903e0 moved configuration management before software selection
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_170413_cm'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstDrive.rb
* 2e07607 checking if snapshots has been enabled
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_170518_snapshots_check'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstStorage.rb
* b405c43 report disk shrinking
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_170609_popup_shrinked_disks'

package/autoyast2.changes
* f3f8d04 merged with CAASP
* f4d1724 Merge pull request #306 from yast/SLE-12-SP2-CASP_bnc1039528_2
* f46330a remove #
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_170609_merged_caasp'

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/storage_proposal.rb, src/modules/AutoinstStorage.rb, test/autoinst_storage_test.rb, test/lib/storage_proposal_test.rb
PBI: https://trello.com/c/B2Qv7y6d/639-5-storageng-proposal-adapt-to-the-situation.
Task: Use the same mechanism in level 1 and 2 of AutoYaST.
It depends on this [PR](https://github.com/yast/yast-storage-ng/pull/296) for yast2-storage-ng.
=> Use new logic to create initial guided proposal

Rakefile, package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/clients/inst_autoinit.rb, src/include/autoinstall/autopart.rb, src/modules/AutoinstGeneral.rb, src/modules/AutoinstPartPlan.rb, src/modules/AutoinstPartition.rb, src/modules/AutoinstSoftware.rb, src/modules/AutoinstStorage.rb, test/AutoinstGeneral_test.rb, test/AutoinstPartPlan_test.rb, test/Makefile.am, test/fixtures/storage/subvolumes.yml, test/include/autopart_test.rb, test/test_helper.rb
It replaces #322 basically because of last conflict and also increases the dependency of yast2-storage to the one used in casp merge yast/yast-storage#289 that has been committed to IBS and synced with OBS.
=> Casp merge

.travis.yml, package/autoyast2.spec
=> Merge SLE-12-SP2

.travis.yml, Dockerfile
=> Merge SLE-12-SP3

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/pkg_gpg_check_handler.rb, test/lib/pkg_gpg_check_handler_test.rb
See [bsc#1054969](https://bugzilla.suse.com/show_bug.cgi?id=1054969).
=> Check CHK_NOSIG result

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/pkg_gpg_check_handler.rb, test/lib/pkg_gpg_check_handler_test.rb
=> Merge handling of CHK_NOSIG result

.travis.yml, Dockerfile
The package was already using the right image but the comment was outdated.
=> Switch to yastdevel/ruby Docker image

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb, test/profile_test.rb
=> Export product name when cloning a profile

src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc
Add missing elements to schema:
* [general => ask-list => ask](https://doc.opensuse.org/projects/autoyast/#CreateProfile.Ask):
* width
* height
* [default_value_script](https://doc.opensuse.org/projects/autoyast/#CreateProfile.Ask.default_value)
* source
* interpreter
* [partitioning](https://doc.opensuse.org/projects/autoyast/#CreateProfile.Partitioning): skip_list stuff (the "Tip: Skipping Devices" infobox)
* Note that `skip_if_equal` is not documented there, but probably should be.
=> Schema fixes

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb, src/modules/AutoinstConfig.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1054400
- Needed by yast/yast-network#572
=> AutoinstConfig: added network_before_proposal (bsc#1054400)

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb, src/clients/inst_autosetup.rb, src/modules/AutoinstConfig.rb, src/modules/AutoinstSoftware.rb, test/AutoinstConfig_tests.rb
- https://fate.suse.com/323450
- https://trello.com/c/EbH6f6Ft
=> Product is installed according to the product selection in the profile

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstPartition.rb, test/AutoinstPartition_test.rb, test/Makefile.am
Merging #355 into `SLE-12-SP3`.
=> Fix subvolumes export

package/autoyast2.changes, package/autoyast2.spec
* 4b3b3ab9 packaging
* d4d6357d cleanup
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_171121_spec_cleanup'

.gitignore, .travis.yml, .yardopts, src/clients/files_auto.rb, src/clients/inst_autopost.rb, src/include/autoinstall/StorageDialog.rb, src/include/autoinstall/classes.rb, src/include/autoinstall/conftree.rb, src/include/autoinstall/dialogs.rb, src/lib/autoinstall/dialogs/disk_selector.rb, src/lib/autoinstall/dialogs/question.rb, src/lib/autoinstall/module_config_builder.rb, src/lib/autoinstall/partitioning_preprocessor.rb, src/lib/autoinstall/pkg_gpg_check_handler.rb, src/lib/autoinstall/storage_proposal.rb, src/modules/AutoInstall.rb, src/modules/AutoinstClass.rb, src/modules/AutoinstClone.rb, src/modules/AutoinstConfig.rb, src/modules/AutoinstDrive.rb, src/modules/AutoinstPartPlan.rb, src/modules/AutoinstScripts.rb, src/modules/AutoinstSoftware.rb, src/modules/AutoinstStorage.rb, src/modules/Profile.rb, src/modules/Y2ModuleConfig.rb
This PR enables `check:doc` in Travis and fixes several documentation issues.
=> Fix documentation

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/partitioning.rnc, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb
* 39b61ddf packaging
* c4731918 added subvolumes_prefix
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_171129_subvolumes_definition'

package/autoyast2.changes, package/autoyast2.spec, src/Makefile.am, src/lib/autoinstall/activate_callbacks.rb, src/modules/AutoinstGeneral.rb, src/modules/AutoinstStorage.rb, test/AutoinstGeneral_test.rb, test/Makefile.am, test/lib/activate_callbacks_test.rb
Honor start_multipath setting.
=> AutoYaST start_multipath support

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb, src/modules/AutoinstSoftware.rb
* 0e933d1c packaging
* 5b5dc05a merge product before package evaluation
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180110_merge_product'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup_upgrade.rb
* a1497b8e adapting to new product handling
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180116_bnc_1075744'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstStorage.rb, test/AutoinstGeneral_test.rb, test/autoinst_storage_test.rb
* 84114001 using ProductFeatures.SetSection instead of ProductFeatures.SetOverlay
=> Using ProductFeatures.SetSection instead of ProductFeatures.SetOverlay

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb
* 3b84134c packaging
* 3f416112 select Product for installation
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180124_selecting_product_for_installation'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb
* 56fa82fd merged with SLES12-SP3
* 9341fe74 Merge pull request #391 from yast/SLE-12-SP3-bnc-1077292
* 3a598f1a merged with SP2
* 2508f78e Merge pull request #390 from yast/SLE-12-SP2-bnc-1077292
* c6195215 splitted into an own call
* 31cc1284 packaging
* ac9f91ee report packages which cannot be selected for installation
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180126_bnc_1077292'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb, test/fixtures/profiles/software.xml
* f3dfd15a merged with SP3
* ba6a1f18 Merge pull request #396 from yast/SLE-12-SP3_bnc_1077292_2
* a4992897 merged with SP2
* 5e61a30c Merge pull request #395 from yast/SLE-12-SP2_bnc_1077292_2
* dd75ba47 adapted
* a5cfc676 packaging
* fb90d75e adapted testcases
* b63ef2c7 new popup layout
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180201_merge_with_sp3'

package/autoyast2.changes, package/autoyast2.spec, src/fillup/sysconfig.autoinstall, src/include/autoinstall/conftree.rb, src/modules/AutoinstConfig.rb
developed mainly for fate#323460
=> Support for disabling edit button

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/conftree.rb, src/modules/AutoinstPartPlan.rb, test/AutoinstPartPlan_test.rb
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1071978 and an additional
problem when browsing the partitioning proposal. By the way, it adds some unit
tests for two AutoinstPartPlan methods.
=> Remove calls to the old API

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_store_upgrade_software.rb
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180226_speedup_pkg_call'

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/activate_callbacks.rb
This is the last bit for https://trello.com/c/ZFRZeyzr/240-3-ruby-code-handle-errors-during-probing
=> Rely on Y2Storage::Callbacks for error handling 

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/activate_callbacks.rb, test/lib/activate_callbacks_test.rb
See openSUSE/libstorage-ng#481.
=> - adapted to new activate callbacks in libstorage-ng

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb, src/clients/inst_autosetup_upgrade.rb
* 63c60393 packaging
* 7d93ba5e using inst_product_license module for showing base license
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180305_confirm_base_product_license'

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/activate_callbacks.rb, test/lib/activate_callbacks_test.rb
Try to unlock devices that are going to be reused.
=> Reuse encrypted devices

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb
* 90ec55bd improved error message if the base product cannot be found
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180320_base_product_not_found'

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb, src/clients/inst_autosetup_upgrade.rb
* 31d5a9b6 packaging
* 4cc486e3 add-on-products ; aborting installation
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180322_add_on_error_handling'

src/clients/inst_autosetup.rb
Fixed some comments for better readability.
=> Fix comment

src/clients/inst_autosetup.rb
=> Fix more comments

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/storage_proposal.rb, test/lib/storage_proposal_test.rb
* Fixes [bsc#1090390](https://bugzilla.suse.com/show_bug.cgi?id=1090390).
* Depends on https://github.com/yast/yast-storage-ng/pull/612.
=> Do not crash when no partitioning proposal is possible

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstStorage.rb, test/autoinst_storage_test.rb
Related to https://github.com/yast/yast-installation/pull/691
=> Do not warn too soon about missing disks

package/autoyast2.spec, src/Makefile.am
* 3e8abe60 Merge branch 'SLE-15-GA'
* 21452195 Merge pull request #436 from yast/SLE-15-GA_1089855_2
* 3ef5fa86 added new directory
* f9f36014 renamed
* bc60d560 added missed files
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180504_sles15_to_master'

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/include/autoinstall/xml.rb, src/modules/AutoinstStorage.rb, test/autoinst_storage_test.rb
* Fixes [bsc#1091669](https://bugzilla.suse.com/show_bug.cgi?id=1091669) and [bsc#1090095](https://bugzilla.suse.com/show_bug.cgi?id=1091669)
* Related to https://github.com/yast/yast-storage-ng/pull/627
* Trello cards: https://trello.com/c/xjlFsCBz and https://trello.com/c/nTbvDnuU/
=> Properly handle subvolumes/subvolumes_prefix

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb
Fixes [bsc#1089547](https://bugzilla.suse.com/show_bug.cgi?id=1089547).
=> DASD and zFCP activation

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb
Cherry-pick #439 to `SLE-15-GA`.
=> Dasd and zfcp activation sle 15

package/autoyast2.changes, package/autoyast2.spec, src/modules/ProfileLocation.rb
* 6d861c28 merged with SLES15
* 16791ca9 Merge pull request #441 from yast/SLE-15-GA-bnc-1094533
* 080c1438 improved value check
* 93afb336 taking basename
* 2079dcba merged with sles15-ga
* 1ca968fd label tag in URL - using libstorage-ng
* 85c5423d Merge pull request #440 from yast/dasd-and-zfcp-activation-sle-15
* cd1ae3b8 Remove not needed assignment
* 9a1ca90d Bump version and update changes file
* fa9db0ea Run DASD and zFCP autoclients when needed
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180604_merged_with_sles15'

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/DriveDialog.rb, src/modules/AutoinstPartPlan.rb, test/AutoinstPartPlan_test.rb
* 721251ab Merge branch 'SLE-15-GA'
* ca6eb97c Merge pull request #443 from yast/SLE-15-GA_bnc_1082556
* 506d2145 Partition configuration: Do not ask for saving values if they have not been changed at all. (bnc#1082556)
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180605_merged_with_sles15'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstall.rb
* cfdc9c4d Merge branch 'SLE-15-GA'
* 90472d87 Merge pull request #445 from yast/SLE-15-GA_bnc_1095113
* 3ffc0cf4 Showing issues onetime only.
=> [Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_180612_merged_with_sles15'

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstallRules.rb, src/modules/AutoinstClass.rb, test/AutoInstallRules_test.rb, test/AutoinstClass_test.rb
=> Merge SLE-15-GA into master

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstPartPlan.rb, src/modules/AutoinstPartition.rb, test/AutoinstPartPlan_test.rb, test/AutoinstPartition_test.rb
=> Merge SLE 12 SP3 into SP4

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb
It is a backport of:
https://github.com/yast/yast-autoinstallation/pull/439/files
=> merge with pr439

package/autoyast2.changes, package/autoyast2.spec, src/fillup/sysconfig.autoinstall
- Trello Card: https://trello.com/c/afBwY7Rc/345-sle-15-ga-as-mu-firewall-ui-support-for-autoyast
=> AY configuration: Permit to edit the firewall module

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/storage_proposal.rb, src/modules/AutoinstStorage.rb, test/autoinst_storage_test.rb
See https://github.com/yast/yast-autoinstallation/pull/501
=> Merge SLE-15-GA

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/storage_proposal.rb, src/modules/AutoinstStorage.rb, test/autoinst_storage_test.rb
See https://github.com/yast/yast-autoinstallation/pull/501.
=> Merge SLE-15-SP1

package/autoyast2.changes, package/autoyast2.spec, src/clients/ayast_setup.rb
This is a back port of https://github.com/yast/yast-autoinstallation/pull/495/files
=> Sle 15 ga bsc 1122660

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/partitioning.rnc
PBI: https://trello.com/c/FsEzGg70/975-3-multi-device-btrfs-support-in-autoyast
Part of https://jira.suse.de/browse/SLE-3877
=> Add multi-device Btrfs elements to the schema

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstLVM.rb
Merging #522 (and #523) into SLE-12-SP5
=> Merge of #522 into SLE-12-SP5 

package/autoyast2.changes, package/autoyast2.spec
https://trello.com/c/Fz8SVjXg/1163-2-osdistribution-p5-1131235-fix-autoyast2-installation-dependencies
https://bugzilla.suse.com/show_bug.cgi?id=1131235
=> Fix dependency

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb
- https://trello.com/c/nkA4Os8Y/1377-5-autoyast-installation-using-the-online-media
- https://jira.suse.com/browse/SLE-7214
- 4.2.12
=> AutoYaST support for the OnlineOnly installation medium (jsc#SLE-7214)

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb, src/modules/AutoinstFunctions.rb, test/AutoinstFunctions_test.rb, test/test_helper.rb
https://trello.com/c/0rbsjTNT/1389-5-autoyast-installation-using-the-offline-media
=> Offline autoinstall

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/partitioning.rnc
See https://github.com/yast/yast-storage-ng/pull/990.
=> Add support for 'crypt_method' element

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstScripts.rb
https://github.com/yast/yast-autoinstallation/pull/new/param-list
https://bugzilla.suse.com/show_bug.cgi?id=1143260
how error report looks like:
=> Param list

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstStorage.rb
Merge with
https://github.com/yast/yast-autoinstallation/pull/542/files
=> Sle 12 sp5 bsc#1155576

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/storage_proposal.rb, src/modules/AutoinstStorage.rb, test/autoinst_storage_test.rb, test/lib/storage_proposal_test.rb
Properly merge proposal settings from the AutoYaST profile (`general/storage/proposal`).
=> Handle proposal settings properly

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/scripts.rnc
See [bsc#1156905](https://bugzilla.suse.com/show_bug.cgi?id=1156905).
Related to https://github.com/yast/yast-firstboot/pull/80 and https://github.com/yast/yast-schema/pull/66.
=>  bsc#1156905: validation problem

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/scripts.rnc
=> bsc#1156905: validation problem (SLE 12 SP5)

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/autopart.rb
=> [SLE-12-SP3] Count extended partition when determining if partitions fit 

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/autopart.rb
=>  [SLE-12-SP5] Count extended partition when determining if partitions fit

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb
related bsc: https://bugzilla.novell.com/show_bug.cgi?id=1159472 https://bugzilla.suse.com/show_bug.cgi?id=1159269
issue:
- wrong assignment caused to not match any name
- wrong call to dependencies that was not initialized in new API
testing:
- unit testing too hard
- manual testing with `yast clone_system` and verify resulting profile
=> Fix pattern clone

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
merge from https://github.com/yast/yast-autoinstallation/pull/566:
Init script: Checking working network with network-online.target
=> Sle 15 sp1 bsc 1164105

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
merge from https://github.com/yast/yast-autoinstallation/pull/567:
Init script: Checking working network with network-online.target
=> Master bsc 1164105

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
It is a follow up of 
https://github.com/yast/yast-autoinstallation/pull/564
We are trying to load network-online.target explicit.
=> loading network-online.target

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
A merge with sles12-SP5
https://github.com/yast/yast-autoinstallation/pull/575
=> Sle 15 ga bsc 1164105 1

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
A merge from SLE-15-GA:
https://github.com/yast/yast-autoinstallation/pull/579
=> Sle 15 sp1 bsc 1164105 1

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
A merge with SLES15-SP1
https://github.com/yast/yast-autoinstallation/pull/580
=> Master bsc 1164105 1

package/autoyast2.changes
=> [SLE-15-SP1] Fix changelog for 4.1.10

modconfig/partitioning.desktop, package/autoyast2.changes, package/autoyast2.spec
Backport changes done in #576 and forgotten in #585
See https://bugzilla.suse.com/show_bug.cgi?id=1168123
=> [SLE-15-SP1] Fix partitioning desktop file

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/classes-use.rnc, src/autoyast-rnc/common.rnc, src/autoyast-rnc/files.rnc, src/autoyast-rnc/general.rnc, src/autoyast-rnc/partitioning.rnc, src/autoyast-rnc/profile-misc.rnc, src/autoyast-rnc/pxe.rnc, src/autoyast-rnc/reporting.rnc, src/autoyast-rnc/scripts.rnc, src/autoyast-rnc/software.rnc, src/lib/autoinstall/activate_callbacks.rb, src/modules/AutoinstClone.rb, src/modules/Profile.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1171412
=> Deduplicate schema

package/autoyast2.changes, package/autoyast2.spec, src/modules/Profile.rb, test/Y2ModuleConfig_test.rb
Fixes build failure in build service.
=> Fix for new parser

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstStorage.rb, test/autoinst_storage_test.rb
Fixes [bsc#1172718](https://bugzilla.opensuse.org/show_bug.cgi?id=1172718) which was introduced by me at #622.
=> bsc#1172718

doc/error_reporting.md
Add a draft document about error reporting.
=> Add an initial document about error reporting

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstClone.rb, test/autoinst_clone_test.rb
trello: https://trello.com/c/1RXM7d8u/1851-8-reduce-profile-i-do-not-export-not-relevant-information#comment-5ee1e470b3a5b661db5b2bcd
=> Reduce profile

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/xml.rb
=> merge SLE-15-SP1 into SLE-15-SP2

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/clone_system.rb, src/modules/AutoinstClone.rb, test/autoinst_clone_test.rb
trello: https://trello.com/c/4ecKNfaX/1920-5-cloned-autoyast-profile-always-contains-unwanted-sections
=> General ay reduce

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/conftree.rb, src/modules/AutoinstClone.rb, src/modules/Profile.rb, test/autoinst_clone_test.rb, test/profile_test.rb
https://trello.com/c/4ecKNfaX/1920-5-cloned-autoyast-profile-always-contains-unwanted-sections
What is goal? Cleaning of AutoinstClone and separate case in Profile for editing profile ( Preparemethod ) and creating new profile ( create method, in old way reset + prepare = true + Prepare )
=> Autoinst clone cleaning

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb, src/clients/inst_autosetup.rb, src/clients/inst_autosetup_upgrade.rb
See yast/yast-autoinstallation#637
Tested with a pre-script that fetch a minimal profile with a ask-list for asking the name of the final profile to be used (with installation & upgrade)
```xml
<?xml version="1.0"?>
<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
<scripts>
<pre-scripts config:type="list">
<script>
<debug config:type="boolean">false</debug>
<feedback config:type="boolean">false</feedback>
<filename>pre-fetch1.sh</filename>
<interpreter>shell</interpreter>
<location><![CDATA[http://192.168.122.1/dud/scripts/pre-fetch.sh]]></location>
<notification>Please wait while pre-fetch.sh is running...</notification>
</script>
</pre-scripts>
</scripts>
</profile>
```
```sh
#!/bin/sh
wget …
```
=> Run pre-scripts just after the profile has been processed (SLE-15-GA)

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb, src/clients/inst_autosetup.rb, src/clients/inst_autosetup_upgrade.rb
=> Merge SLE-15-GA into SLE-15-SP1

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autosetup.rb, src/lib/autoinstall/clients/inst_autoinit.rb, src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
=> Merge SLE-15-SP2 int o master

src/lib/autoinstall/auto_sequence.rb, src/lib/autoinstall/clients/autoyast.rb, src/lib/autoinstall/clients/clone_system.rb, test/lib/clients/autoyast_test.rb
Missing updates from a code review related to #646.
=> Improve CLI updates

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autopost.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1174069
=> Autopost crash

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoInstall.rb
A merge from:
SLES15-SP1: https://github.com/yast/yast-autoinstallation/pull/657
=> Sle 15 sp2 bsc 1145269

.yardopts, README.md, doc/error_reporting.md, doc/multipath.md, doc/network_scenarios.md, doc/profile_handling.md, doc/validation.md
Documents how the profile is handled.
Trello: https://trello.com/c/mC7fZeip/1970-5-research-document-the-autoyast-profile-fetching-process
<details>
<summary>Rendered documentation</summary>
</details>
=> Add a document describing how the profile is handled

test/AutoInstall_test.rb
Ensure the needed Report level for the test.
=> Fix AutoInstall#valid_imported_values test

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstScripts.rb
....for :
AY: Calling of post-partitioning scripts moved from dropped inst_autoimage to inst_kickoff
=> adapted docu

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/autosetup_helpers.rb, src/lib/autoinstall/clients/inst_autosetup.rb, test/lib/autosetup_helpers_test.rb, test/lib/clients/inst_autosetup_test.rb
Runs firewall's auto client in the first stage
=> Firewall in first stage

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/storage_controller.rb, test/lib/storage_controller_test.rb
Do not rely on `SectionWithAttributes#section_name` method.
=> Fix storage controller

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/xml.rb
=> bsc#1175714: export postpartitioning-scripts section properly

package/autoyast2.changes, package/autoyast2.spec, src/include/autoinstall/xml.rb
=>  bsc#1175714: export postpartitioning-scripts section properly

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup.rb, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb
=> Merge SLE-15-SP2 into master

src/modules/AutoInstallRules.rb, test/AutoInstallRules_test.rb
Improve `AutoInstallRules` test coverage.
=> Extend AutoInstallRules tests

src/modules/AutoInstallRules.rb, test/AutoInstallRules_test.rb
The code for handling **AutoYaST** Rules and Classes have a general lack of unit tests.
- https://trello.com/c/TQPehs2U/2015-8-refactor-the-autoyast-profile-loading-process
Added unit tests for the Process method improving the `AutoInstallRules` test coverage.
=> Cleanup and unit test for AutoInstallRules#Process

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autoinit.rb
=> Import initial configuration from the profile when modified by pre-scripts (SLE-15-SP1)

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/clone_system.rb, test/lib/clients/clone_system_test.rb
Related to [bsc#1174202](https://bugzilla.suse.com/show_bug.cgi?id=1174202) and https://github.com/yast/skelcd-control-leanos/pull/60.
=> Set permissions 0o600 to generated profile when cloning

test/lib/widgets/storage/shared_examples.rb
* Related to https://github.com/yast/yast-yast2/pull/1104
=> Fix storage shared examples

package/autoyast2.changes, package/autoyast2.spec
=> Bump version and update changes

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc
Fix [bsc#1176973](https://bugzilla.suse.com/show_bug.cgi?id=1176973).
=> Drop mouse element

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc
=> Drop mouse element (master)

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/general.rnc
Partially fixes [bsc#1176595](https://bugzilla.suse.com/show_bug.cgi?id=1176595) by adding missing elements to the general/mode element.
=> General mode validation

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/script.rb, src/modules/AutoinstScripts.rb, test/AutoinstScripts_test.rb
Fixes [bsc#1177057](https://bugzilla.suse.com/show_bug.cgi?id=1177057).
=> bsc#1177057: do not report an error when a script did not run

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/partitioning.rnc
Extend schema to support Btrfs quotas: See https://github.com/yast/yast-storage-ng/pull/1186 for reference.
=> Add Btrfs quotas support

src/lib/autoinstall/clients/inst_autoinit.rb, src/modules/AutoinstFunctions.rb, test/lib/clients/inst_autosetup_upgrade_test.rb
https://github.com/yast/yast-autoinstallation/pull/new/SLE-15-SP2-bsc-1175876-rubocop
=> Fixed rubocop for bsc-1175876

test/test_helper.rb
Temporary mock for all Reports in test due to interdependencies in autoyast testsuite.
=> big mock of report

src/clients/inst_autosetup.rb
Fix a misplaced call to NextStage and remove a leftover.
=> Fix misplaced NextStage call

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup.rb
Merge #737 and #738 into `master`.
=>  bsc#1183042: postpone importing security settings (master)

Rakefile, package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/README.md, src/autoyast-rnc/general.rnc
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1183512#c8
tested manually against profile user reported as problematic.
testing profile:
```xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE profile> 
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns"> 
<general> 
<semi-automatic config:type="list"> 
<semi-automatic_entry>networking</semi-automatic_entry> 
<semi-automatic_entry>scc</semi-automatic_entry> 
<module>partitioning</module> 
</semi-automatic> 
</general> 
</profile>
```
Pre-existing documentation: https://documentation.suse.com/sles/15-SP2/single-html/SLES-autoyast/index.html#CreateProfile-General-semi-automatic
=> Fix schema

.github/workflows/ci.yml, Rakefile
merge to master of https://github.com/yast/yast-autoinstallation/pull/745
=> Fix crash master

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/autosetup_helpers.rb, test/lib/autosetup_helpers_test.rb
=> Merge SLE-15-SP2 into SLE-15-SP3

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup_upgrade.rb, test/lib/clients/inst_autosetup_upgrade_test.rb
=> Process PackagesProposal packages during autoupgrade (master)

package/autoyast2.changes, package/autoyast2.spec
=> Merge SLE-15-SP3 into master

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstFile.rb, test/autoinst_file_test.rb
Merges #781 into `SLE-15-SP3`.
=> bsc#1188357: copy files to the right location when file_location is given

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/rules.rnc, src/modules/AutoinstFile.rb, src/modules/AutoinstGeneral.rb, test/AutoinstGeneral_test.rb, test/autoinst_file_test.rb
Merges #782 and #777 into `master`.
=> Sync SLE-15-SP3 and master

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/script.rb, src/modules/Profile.rb, test/lib/script_test.rb, test/profile_test.rb
Merging SP3 to master:
- #785 
- #784
=> [master] Add "final_reboot" and "final_halt" scripts only once (bsc#1188356) + copy init-scripts to the target system (bsc#1188360)

package/autoyast2.changes
- The SP4 submit has been declined
- See https://build.suse.de/request/show/246950 for details
- The missing changes were copied from https://build.suse.de/package/show/SUSE:SLE-15-SP3:GA/autoyast2
=> Added some missing SP3 changes

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/rules.rnc, test/AutoinstScripts_test.rb, test/lib/autoinstall/script_runner_test.rb
* Merge #792 to `master`.
* Add tests from #789. Bear in mind that the bug the original PR fixed is not reproducible in `master`.
=> Update rules.xml schema (bsc#1190696)

test/lib/clients/clone_system_test.rb
An attempt to fix https://build.suse.de/package/live_build_log/Devel:YaST:SLE-15-SP3/autoyast2/SUSE_SLE-15-SP3_Update/x86_64.
=> Fix clone_system tests

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup.rb, test/lib/clients/inst_autosetup_test.rb
=> bsc#1192185: Do not process the <add-on> section again (master)

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup_upgrade.rb, test/lib/clients/inst_autosetup_upgrade_test.rb
=> Merge SLE-15-SP3 into 'master'

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autoinit.rb, src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
=> Online autoupgrade workflow (master).

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/pkg_gpg_check_handler.rb, src/modules/AutoInstall.rb, test/AutoInstall_test.rb, test/lib/pkg_gpg_check_handler_test.rb
=> Fix addons signature handling (master)

package/autoyast2.changes, package/autoyast2.spec, src/clients/inst_autopost.rb, src/include/autoinstall/dialogs.rb, src/lib/autoinstall/clients/ayast_setup.rb, src/lib/autoinstall/clients/clone_system.rb, src/lib/autoinstall/package_searcher.rb, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb, test/lib/clients/ayast_setup_test.rb, test/lib/clients/clone_system_test.rb
Adapt to `Package` and `PackageSystem` changes. See https://github.com/yast/yast-yast2/pull/1219 for further information.
=> Use `Package` instead of `PackageSystem`

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
See https://github.com/yast/yast-installation/pull/1024 for more details.
- https://bugzilla.suse.com/show_bug.cgi?id=1195059
=> Fix Second Stage timeout when using ssh

package/autoyast2.changes, package/autoyast2.spec, scripts/autoyast-initscripts.service
See https://github.com/yast/yast-autoinstallation/pull/829.
=> Avoid login (port to SP4)

package/autoyast2.changes, package/autoyast2.spec, src/clients/ayast_setup.rb, src/lib/autoinstall/clients/ayast_setup.rb, test/lib/clients/ayast_setup_test.rb
This PR fixes [bsc#1196566](https://bugzilla.suse.com/show_bug.cgi?id=1196566) (confirmed by the reporter).
=> bsc#1196566: properly handle the dopackages option

package/autoyast2.changes, package/autoyast2.spec, src/clients/ayast_setup.rb, src/lib/autoinstall/clients/ayast_setup.rb, test/lib/clients/ayast_setup_test.rb
=> bsc#1196566: properly handle the dopackages option (master)

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/rules.rnc, src/lib/autoinstall/y2erb.rb
Merge #836 and #837 into `SLE-15-SP4`
=> Merge SLE-15-SP3 into SLE-15-SP4

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/rules.rnc, src/lib/autoinstall/y2erb.rb
Merge #836, #837 and #838 to `master`.
=> Merge SLE-15-SP4 to master

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autoinit.rb, test/lib/clients/inst_autoinit_test.rb
- Just merging #840 from SP4 to master
=> [master] SLE Micro registration fix

package/autoyast2.changes, package/autoyast2.spec, test_xml/cc.xml, test_xml/cobbler.xml
See https://github.com/yast/yast.github.io/pull/336 for details
=> Replaced egrep with grep -E

src/clients/inst_autopost.rb
Related to #849: re-import general settings so you can modify them using <ask-list>.
=> Re-import general settings

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/autoinst_profile/ask_section.rb, src/lib/autoinstall/autoinst_profile/ask_selection_entry.rb
=> bsc#1204448: allow empty values for some <ask> values

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/autosetup_helpers.rb, src/lib/autoinstall/clients/inst_autosetup.rb, test/lib/autosetup_helpers_test.rb, test/lib/clients/inst_autosetup_test.rb
Merge security policies and a kdump fix into `master`
=> Merge security policies and a kdump fix into master

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
- Just merging https://github.com/yast/yast-autoinstallation/pull/863 to `master`
=> [master] Rebuild the RPM database during upgrade (--rebuilddb) (bsc#1209565)

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb
- Just merging PR#867 to SP4, see more details in #867
- Added an unit test (SP3 does not test this functionality)
Here are updated screenshots from the manual test.
|Original|Fixed|
|---|---|
|![ay_product_selection_broken_summary_sp4](https://github.com/yast/yast-autoinstallation/assets/907998/9e1c238c-f508-4661-b2a0-df3199e45ee2)|![ay_product_selection_fixed_sp4](https://github.com/yast/yast-autoinstallation/assets/907998/7a576e31-4764-4f82-aa92-a45aba37bf65)|
|![ay_product_selection_broken_sp4](https://github.com/yast/yast-autoinstallation/assets/907998/5bd903d0-fa88-48e5-b875-cc9e6aadb174)|![ay_product_selection_fixed_summary_sp4](https://github.com/yast/yast-autoinstallation/assets/907998/23427c72-5383-435a-9fff-75baa38bf8e9)|
=> [SLE15-SP4] Properly install the selected products (bsc#1202234)

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb
- Just merging PR#868 to SP5, see more details in #868
Here are updated screenshots from the manual test.
|Original|Fixed|
|---|---|
|![ay_product_selection_broken_sp5](https://github.com/yast/yast-autoinstallation/assets/907998/5fb4d384-46a4-46b3-9623-7976b134c714)|![ay_product_selection_fixed_sp4](https://github.com/yast/yast-autoinstallation/assets/907998/de70f426-1b3c-4fc4-855d-2cbaaeea2958)|
|![ay_product_selection_broken_sp5_details](https://github.com/yast/yast-autoinstallation/assets/907998/0978587b-abc7-4390-8a56-26c82a15359d)|![ay_product_selection_fixed_sp5_details](https://github.com/yast/yast-autoinstallation/assets/907998/837c76b3-2bca-40e4-95b3-a71951fc87b7)|
=> [SLE15-SP5] Properly install the selected products (bsc#1202234)

package/autoyast2.changes, package/autoyast2.spec, src/modules/AutoinstSoftware.rb, test/AutoinstSoftware_test.rb
- And finally merging PR#868 to `master`, see more details in #868
=> [master] Properly install the selected products (bsc#1202234)

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
- Just backporting https://github.com/yast/yast-autoinstallation/pull/863 to SLE15-SP4
=> [SLE15-SP4] Rebuild the RPM database during upgrade (--rebuilddb) (bsc#1209565)

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/partitioning.rnc
This is a merge of #872 to the master branch. See the original pull request for details.
Bear in mind this is the first merge ever from SLE-15-SP6 into master in this repository.
=> New LUKS-related elements in the master schema of the <partition> section

package/autoyast2.changes, package/autoyast2.spec, src/autoyast-rnc/partitioning.rnc, src/include/autoinstall/xml.rb
=> Added pervasive encryption fields (master)

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup.rb
=> Instantiate the default security settings before importing the profile (bsc#1231490) - master branch

package/autoyast2.changes, package/autoyast2.spec, src/lib/autoinstall/clients/inst_autosetup.rb
=> Move the firewall configuration between security and sotware in inst_autosetup (bsc#1243185) - Master

package/autoyast2.changes
Don't know why it is failing so, just run the /usr/lib/obs/service/source_validators/helpers/fix_changelog for #886
=> Just make the osc validator happy
