.travis.yml
package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/io.rb
src/modules/AutoInstallRules.rb

autoyast=file:///<autoinst.xml> : Mount the installation source
in order to copy AutoYaST configuration file into inst_sys.
(bnc#908271)

Bug 908271

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstStorage.rb

Checking if the disk is -partitionable- instead of checking if it is a real disk.

Bug 909349; Multipath in AutoYaST

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoInstallRules.rb
test/AutoInstallRules_test.rb

`#ProbeRules` crashes when `SCR.Read(path(".content.DISTRO")` returns nil. In openSUSE 13.2, Tumbleweed and SLES 12, calling `yast2 ayast_probe` exhibits this behaviour. Hopefully this PR fix that issue.
Anyway, this PR seems to be just a workaround. I mean: I'm not sure that asking for '.content.DISTRO' in this context is ok. Thoughts?
BTW, I've moved the initialization of instance variable to a `#reset` method so I could test `#ProbeRules` with different scenarios (it does nothing when `@ATTR` is not empty). I dunno if I must write a test for that new method (it contains just a bunch of initializations).

Avoid yast2 ayast_probe crashing when finding the installed distro

---

src/modules/AutoinstClass.rb
test/AutoinstClass_test.rb
test/fixtures/output/partitions-dontmerge.xml
test/fixtures/output/partitions-merged.xml
test/fixtures/profiles/partitions.xml

Hi,
This PR is the second part of #101 so it refactors the rest of the AutoinstClass class.
Thanks.

Refactor the rest of AutoinstClass

---

src/include/autoinstall/ask.rb
test/include/ask_test.rb
test/include/autoinstall/AutoinstallAskInclude_test.rb
test/test_helper.rb

I've seen on [bug #925879](https://bugzilla.suse.com/show_bug.cgi?id=925879), there are some glitches about feedback when an script is running. This PR includes:
* A new feedback dialog just to notice the user that some script is running.
* A little bit wider dialog to show the script's output.
* BTW, some tests have been added about the basics of askDialog method for AutoYaST.
* Added also some comments because askDialog is a huge method and is rather easy to get lost at some point.

Improve feedback when executing scripts

---

src/include/autoinstall/ask.rb
test/include/ask_test.rb

AutoinstallAskInclude#askDialog use always the same id for password fields (thanks @jreidinger for pointing that).

Fix a potential Id collision on password widgets

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb
src/modules/Profile.rb
src/modules/Y2ModuleConfig.rb
test/Makefile.am
test/Y2ModuleConfig_test.rb
test/fixtures/desktop_files/desktops.yml
test/fixtures/profiles/unhandled_and_obsolete.xml

- We have dropped support of some Yast modules recently, e.g. *sshd* and we need to let users know that they should configure these pieces differently
- AutoYast now reports two types of sections: unsupported ~ those that we've dropped, and unknown ~ those that do not seem to be handled by any currently installed Yast module (this information is in particular desktop file)
- AutoYast handles some sections by itself, so they are excluded from the report
- This is a big change and I do not want to put it into SLE 12 (SP1 is fine)
- bnc#925381

Reporting unknown and unsupported profile sections

---

test/AutoinstClass_test.rb
test/Makefile.am

This PR should fix some issues when running AutoinstClass tests from the `test/` directory. BTW, it converts to constants all those paths.

Fix AutoinstClass tests paths

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/autopart.rb

PReP partitions are raw partitions, and shouldn't be formated.
Extend fsid_bios_grub check with GPT and DOS PReP partitions.
bsc#927748
Signed-off-by: Dinar Valeev <dvaleev@suse.com>

Fix PReP format.

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb

Just use the `snapshots_finish` client (available in yast-installation) to perform the snapshot.

Add support for performing fs snapshots at the end of install/upgrade

---

src/clients/inst_autosetup.rb
src/modules/AutoInstall.rb
src/modules/Profile.rb
test/AutoInstall_test.rb
test/profile_test.rb

* To fix a circular dependency problem, defines the second_stage_required? function in AutoInstall.

"Copy" second_stage_required? to AutoInstall

---

package/autoyast2.changes
package/autoyast2.spec
src/Makefile.am
src/clients/inst_autosetup.rb
src/modules/AutoInstall.rb
src/modules/AutoinstFunctions.rb
src/modules/Profile.rb
test/AutoinstFunctions_test.rb
test/profile_test.rb

* This bug prevented running configuration clients during 2nd stage.
* Move offending code to a new class AutoinstFunctions (analogue to InstFunctions in yast2-installation).
* Fixes [bsc#944770](https://bugzilla.suse.com/show_bug.cgi?id=944770).

Fix premature loading of AutoInstall

---

package/autoyast2.changes
package/autoyast2.spec

lib directory contains `pkg_gpg_checker_handler`, which is used by `AutoInstall.rb`.

Move lib directory to autoyast2-install package

---

package/autoyast2.changes
package/autoyast2.spec

It should solve [bsc#953162](https://bugzilla.suse.com/show_bug.cgi?id=953162).

Add a missing dependency on yast2-pkg-bindings

---

package/autoyast2.changes
package/autoyast2.spec

Fixes [bsc#953162](https://bugzilla.suse.com/show_bug.cgi?id=953162)

Add missing yast2-pkg-bindings dependency

---

src/autoyast-rnc/scripts.rnc

network_needed is supposed to be optional, as stated in the documentation.
I'm not updating the changes or spec file as it was changed in a previous commit and I haven't updated the devel project in IBS yet (I'll do it after this change is merged).

network_needed should be optional

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb

* 81b09eb packaging
* b71ef56 network services has to be restarted again because there is no dependencies on YaST2-Seconde-Stage.service anymore. This should be much easier now

[Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_151217_cleanup_service_dependencies'

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstScripts.rb

* b1ab881 typo
* 32c40d7 merged with SLES12-SP1
* 63aeb46 Merge pull request #174 from yast/bug_960907
* 26a5418 packaging
* 2e02a63 using AutoinstConfig.destdir
* 31471af moved to initscripts_dir
* 0fcb2e0 added dest. Dir

[Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160112_bnc_960907'

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/Profile.rb

This solves bug [bsc#962526](https://bugzilla.opensuse.org/show_bug.cgi?id=962526).

Add 'init' to the list of generic AutoYaST sections

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb
test/AutoInstallRules_test.rb
test/AutoinstSoftware_test.rb

The error has been seen in the integration test. Network has not been available anymore with the keep_install flag. After rebooting network has been available. So I added the previous fix again, with which all network services will not be restarted after second stage. After that everything has worked again.
* cb5c5f2 packaging
* a7d4945 layout
* 1185617 enable ignoring restart of networking services

[Review] Request from 'schubi2' @ 'yast/yast-autoinstallation/review_160223_no_network_restart'

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/ssh-import.rnc

* The latest version uses 'copy_config' instead of only 'config'.

Fix ssh_import schema

---

doc/Makefile.am
doc/autodocs/Makefile.am
package/autoyast2.changes

I'm not releasing a new version because 3.1.130 was rejected by Jenkins.

Stop generating autodocs

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoinit.rb

during profiling installation I found these two sleep which looks useless and it is in fact called twice, so it safe 4 second when removed and autoyast installation pass.

Installation optimize

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstScripts.rb

[bsc#986049](https://bugzilla.suse.com/show_bug.cgi?id=986049)

Bug 986049 sp1

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/ask.rb
test/include/ask_test.rb

- Added new [Stop] button for <ask> dialogs with timeout. The button shows the current time in seconds till the automatic timeout ([bsc#990114](https://bugzilla.suse.com/show_bug.cgi?id=990114))
- More possible user actions can now stop the execution to prevent from timeout (also bsc#990114)
- Added new unit-test (3x)
- Adjusted old tests
- TextEntry is now InputField (since something like 2005)

Fixing timeout issues in <ask> dialogs

---

.travis.yml
package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstConfig.rb
test/AutoinstConfig_tests.rb
test/Makefile.am

- [bsc#987858](https://bugzilla.suse.com/show_bug.cgi?id=987858)
- It has been reported that `autoyast=usb` has been working since
SLE9, but stopped working in SLE12. This patch reintorduces
this possibility again
- `autoyast=usb` is internally converted into `autoyast=usb:///autoinst.xml`
- Manually tested
- Patch contains a new test-case
- Refactoring included

Reintroduced autoyast=usb as a valid URL to AutoYaST profile

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/autoinst_dialogs.rb
src/modules/ProfileLocation.rb

This change is part of this PR https://github.com/yast/yast-installation/pull/424 and in general part of the new update installer refactorization https://github.com/yast/yast-installation/pull/422

Profile Location: Use Report instead of Popup to not block AutoYast

---

package/autoyast2.changes
package/autoyast2.spec
src/Makefile.am
src/desktop/clone_system.desktop

I'm backporting the fix for [bsc#985621](https://bugzilla.suse.com/show_bug.cgi?id=985621) because, although it was reported in SLE 12 SP2, it was only fixed in `master`.

SLE 12 SP2 merge

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/Profile.rb
src/modules/Y2ModuleConfig.rb
test/Y2ModuleConfig_test.rb
test/profile_test.rb

This PR allow hidden modules to be cloned ([bsc#1008301](https://bugzilla.suse.com/show_bug.cgi?id=1008301)).
Additionally, it adds a new `X-SuSE-YaST-AutoInstResourceAliases` element to desktop files so [bsc#887115](https://bugzilla.suse.com/show_bug.cgi?id=887115) can be fixed. The idea is that we can get rid of `runlevel.desktop` and just specify `X-SuSE-YaST-AutoInstResourceAliases=runlevel` in `services-manager.desktop` (implemented in https://github.com/yast/yast-services-manager/pull/114).

Clone hidden

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstStorage.rb

Fix [bsc#1012328](https://bugzilla.suse.com/show_bug.cgi?id=1012328). Covered by integration tests: https://github.com/yast/aytests-tests/pull/48.
When using Btrfs, if subvolumes are not specified, the default set will be created. But what if you do not want any subvolume to be created (an empty list will be removed when importing the profile)? You can work around that by setting the subvolumes list as this:
```xml
<subvolumes config:type="list">
<subvolume>/</subvolume>
</subvolumes>
```

Create default subvolumes

---

check_schema.sh

- check that `trang` is actually installed
- be more verbose (print progress and the result)
- save the RNG files to /dev/null (not needed anyway, avoid save&remove)
See this example output: https://travis-ci.org/yast/yast-autoinstallation/builds/189202776#L1819

Improve the check_schema.sh script

---

.travis.yml
Dockerfile
Rakefile
package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoInstallRules.rb
test/AutoInstallRules_test.rb
test/AutoInstall_test.rb
test/AutoinstClass_test.rb
test/AutoinstConfig_tests.rb
test/AutoinstFunctions_test.rb
test/AutoinstGeneral_test.rb
test/AutoinstPartPlan_test.rb
test/AutoinstSoftware_test.rb
test/Y2ModuleConfig_test.rb
test/include/ask_test.rb
test/include/autopart_test.rb
test/lib/module_config_builder_test.rb
test/profile_test.rb

Configure travis and adapt rakefile to use storage-ng OBS project. Remove dependencies of yast2-storage.
Tests are temporally disabled in order to travis passes. To able them again, necessary dependencies will be added in another PR. 
https://trello.com/c/qsxBrzIE/499-2-storageng-get-failing-openqa-test-fixed-by-adjusting-autoinstallrules-to-storage-ng

Hacks to avoid old Storage usage

---

package/autoyast2.changes
package/autoyast2.spec
src/Makefile.am
src/lib/autoinstall/storage_proposal.rb
src/modules/AutoinstStorage.rb
test/Makefile.am
test/autoinst_storage_test.rb
test/lib/storage_proposal_test.rb

When a `partitioning` section is specified, the partitioning will be performed by `Y2Storage::AutoInstProposal`. Depends on https://github.com/yast/yast-storage-ng/pull/259.
Travis is failing because the docker image does not contain the latest yast2-storage-ng version.

Storage-ng custom (level-3) partitioning

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstPartition.rb
test/AutoinstPartition_test.rb
test/Makefile.am

If there are not subvolumes, export an empty subvolumes list instead of removing it completely.

Fix subvolumes export

---

package/autoyast2.changes
src/modules/AutoinstConfig.rb
test/AutoinstConfig_tests.rb

Unit tests were working because the class was loaded in the test itself.
I am not increasing version number because I plan to merge #358 today too.

Fix require of y2packager/product

---

package/autoyast2.changes
package/autoyast2.spec
src/Makefile.am
src/clients/inst_autosetup.rb
src/lib/autoinstall/dialogs/question.rb
src/lib/autoinstall/storage_proposal.rb
src/lib/autoinstall/storage_proposal_issues_presenter.rb
src/modules/AutoinstStorage.rb
test/Makefile.am
test/autoinst_storage_test.rb
test/lib/dialogs/question_test.rb
test/lib/storage_proposal_issues_presenter_test.rb
test/lib/storage_proposal_test.rb
test/test_helper.rb

This PR adds error reporting capabilities to AutoYaST when creating the partitioning plan during installation.
In SLE 12, when something goes wrong, you have always something like this:
In SLE 15, AutoYaST:
* will provide better error messages.
* if some non-critical setting is wrong, it will warn the user if she/he wants to continue the installation.
Finally, this feature honors the "reporting" section of an AutoYaST profile, so you can hide the warning messages or apply a timeout to them.

AutoYaST error reporting

---

package/autoyast2.spec

It depends on [yast2-storage-ng error reporting](https://github.com/yast/yast-storage-ng/blob/d387eda26dce35b925dc65b95b1e6ff70fd7c473/package/yast2-storage-ng.changes#L17) capabilities.

Update yast2-storage-ng dependency

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/storage_proposal.rb
src/lib/autoinstall/storage_proposal_issues_presenter.rb
src/modules/AutoinstPartPlan.rb
src/modules/AutoinstStorage.rb
test/autoinst_storage_test.rb
test/lib/storage_proposal_issues_presenter_test.rb
test/lib/storage_proposal_test.rb

This PR adds some improvements:
* Better error messages adding some information about which section failed.
* Do not add an error when the root partition is not proposed (it is already handled by yast2-storage-ng).

Improve errors reporting

---

test/AutoinstPartPlan_test.rb

It should fix https://build.suse.de/package/live_build_log/Devel:YaST:Head/autoyast2/SUSE_SLE-15_GA/s390x
It looks like, on s390 architectures, we rely on udev links. See https://github.com/yast/yast-storage-ng/blob/master/src/lib/y2storage/autoinst_profile/drive_section.rb#L155

Fix building in s390 architectures

---

package/autoyast2.changes
package/autoyast2.spec
src/Makefile.am
src/lib/autoinstall/dialogs/disk_selector.rb
src/lib/autoinstall/partitioning_preprocessor.rb
src/lib/autoinstall/storage_proposal_issues_presenter.rb
src/modules/AutoinstStorage.rb
test/Makefile.am
test/autoinst_storage_test.rb
test/lib/dialogs/disk_selector_test.rb
test/lib/partitioning_preprocessor_test.rb
test/lib/storage_proposal_issues_presenter_test.rb
test/test_helper.rb

There is a nice (and undocumented feature) which allows the user to select which disk to use at installation time (setting `device` AutoYaST element to `ask`). The feature was removed as part of the old code clean-up and now we have brought it back using the new storage layer.

AutoYaST device=ask support

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb
src/clients/inst_autosetup_upgrade.rb
src/modules/AutoinstStorage.rb
test/AutoinstGeneral_test.rb
test/autoinst_storage_test.rb

It fixes [bsc#1073548](https://bugzilla.suse.com/show_bug.cgi?id=1073548).There were two problems which prevented `this setting to work:
* When add-ons are reintegrated, the overly in ProductFeatures is destroyed. So now we are applying the overly after the add-ons are reintegrated.
* The setting was not interpreted correctly (it is suppose to be a boolean, not the real subvolume name).

Fix btrfs_set_default_subvolume_name

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup_upgrade.rb
test_xml/upgrade.xml

AutoYaST counterpart for https://github.com/yast/yast-update/pull/90
Yes, I know that .rnc profile changes are pending, I would like to update the file after doing some tests just in case it shows we need to revert.

always upgrade system via equivalent of 'zypper dup', removing respective control from the profile (bsc#1071708)

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoinit.rb
src/modules/AutoinstConfig.rb
src/modules/AutoinstFunctions.rb
src/modules/AutoinstSoftware.rb
test/AutoinstConfig_tests.rb
test/AutoinstFunctions_test.rb

It fixes [bsc#1075334](https://bugzilla.suse.com/show_bug.cgi?id=1075334).
The problem was caused by a circular dependency between `Profile` and `AutoinstConfig`. I've moved `check_second_stage_environment` and `selected_product` (and related private functions) from `AutoinstConfig` to `AutoinstFunctions` (which already contained a method to check whether the second stage was needed). Now, `AutoinstConfig` does not depend on `Profile` anymore.
Please, see also https://github.com/yast/yast-installation/pull/641 and https://github.com/yast/yast-registration/pull/349.

Fix /tmp/profile

---

package/autoyast2.changes
src/modules/AutoinstSoftware.rb

- Unfortunately it's not easy to get the details of solver failure
- This is related to [this openQA issue](https://openqa.suse.de/tests/1396302#step/installation/43)
- The `pkg-bindings` [save some details into a file](https://github.com/yast/yast-pkg-bindings/blob/2f303c70e552a11d96a7fd7c92399cf030cbfcfa/src/Package.cc#L1979) so just display it
- No version bump as this is just a minor enhancement

Display more details when the package solver fails

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_store_upgrade_software.rb
src/modules/AutoinstSoftware.rb
test/AutoinstSoftware_test.rb

- See https://bugzilla.suse.com/show_bug.cgi?id=1077882
- Avoid using `Pkg.ResolvableProperties("", :package, "")` calls which require too much memory (returns *all* packages at once)
- Rather get the package list via `Pkg.GetPackages` and call `Pkg.ResolvableProperties` for each package separately
- So instead working with one huge list we process many smaller ones, the advantage is that the memory for the smaller parts can be reused in the loop decreasing the overall memory requirement
- Not tested, let's see if that helps in OpenQA...
- 4.0.26

Decrease memory consumption (bsc#1077882)

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstSoftware.rb
test/AutoinstSoftware_test.rb

- Fix up for #393 - the `clone_system` client spent several minutes processing the packages, with this fix it takes just few seconds as before
- The `ResolvableProperties` call is quite expensive, it returns a lot of details for each package which we do not need here
- Replaced by `PkgPropertiesAll` which returns much less data so it's faster to create a process
- Depends on https://github.com/yast/yast-pkg-bindings/pull/95 which adds the required data
- 4.0.27

Speed optimization for the previous fix (bsc#1077882)

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstFunctions.rb
src/modules/AutoinstSoftware.rb
test/AutoinstFunctions_test.rb
test/AutoinstSoftware_test.rb

The cloned profile contains a wrong base product name:
```xml
<products config:type="list">
<product>SLED15</product>
</products>
```
it should be a simple name without version:
```xml
<product>SLED</product>
```
- Use the `"name"` attribute at cloning (it is expected at installation).
- https://bugzilla.suse.com/show_bug.cgi?id=1084259
- 4.0.38

Fixed cloning of the base product name (bsc#1084259)

---

doc/profile_changes_SLE15.md
package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/xml.rb

- [Trello Card](https://trello.com/c/o6xMc6sL/1374-0-ostumbleweed-p1-1013047-generated-autoyast-profile-does-not-validate-firewall)
- https://bugzilla.suse.com/show_bug.cgi?id=1013047

Added more list entry names to be used instead of 'listentry'

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb
src/modules/AutoinstStorage.rb
test/autoinst_storage_test.rb

* Read product features earlier.
* Merge (not replace) storage settings with `general/storage` values from the profile.
Fixes [bsc#1085755](https://bugzilla.suse.com/show_bug.cgi?id=1085755).

Fix product features read

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup_upgrade.rb

- We had a bug report that interactive upgrade did not install the products for new SLE15 modules: https://bugzilla.suse.com/show_bug.cgi?id=1086818
- I have found the very same issue also in the AutoYaST autoupgrade mode, see the screenshots below
- It turned out that the products were correctly selected by the registration module, but they were reset later by the AutoYaST autoupgrade code and lost
- This one liner patch removes that reset
- This part of the code was [added 7 years ago](https://github.com/yast/yast-autoinstallation/commit/0a57dda918b1d0e820d783d6dde60c6d74c9d170#diff-66d4410704185b63421d5ab3f1d517f1R311) (looks like a copy&paste from `update_proposal.ycp` client)
- Originally the code stored the selected products and restored them after the reset, this is [still done …

Install the module products also in AutoYaST autoupgrade (related to bsc#1086818)

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoInstallRules.rb
src/modules/AutoinstClass.rb
test/AutoInstallRules_test.rb
test/AutoinstClass_test.rb

- Trello Card: https://trello.com/c/6mrdmQ1R/194-l3-bug-1104655-autoyast-error-on-merging-profiles-rules
- https://bugzilla.suse.com/show_bug.cgi?id=1104655
There have been some changes in the xslt libraries regarding to the recursion detection which probably are also the source of this bug as we can see in link below:
https://build.opensuse.org/package/rdiff/devel:libraries:c_c++/libxslt?linkrev=base&rev=65
I have just cleaned up a little bit the method with the merge responsibility mostly as it was cleaned for Classes handling.

Merge profiles: increase the default --maxdepth option

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstPartPlan.rb
src/modules/AutoinstPartition.rb
test/AutoinstPartPlan_test.rb
test/AutoinstPartition_test.rb

In SLE 12, the `partition_type` element is ignored when exporting unless it is `primary` (?). It causes problems like [bsc#1091415](https://bugzilla.suse.com/show_bug.cgi?id=1091415). With this change, AutoYaST will always export the `partition_type` when using a MS-DOS partition table.

Export partition_type when cloning

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/partitioning.rnc

Add support to put `raid_options` within the `<drive>` section in order to support the new style to define a RAID:
```xml
<partitioning>
<drive>
<device>/dev/md/0</device>
<raid_options>
<raid_type>raid1</raid_type>
</raid_options>
<partitions config:type="list">
</partitions>
</drive>
</partitioning>
```

Allow <raid_options> to appear under <drive> sections

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstFunctions.rb
test/AutoinstFunctions_test.rb

https://bugzilla.opensuse.org/show_bug.cgi?id=1125959
> AutoinstFunction#base_product_name was crashing when given profile had
not a valid `software` section, which could happen due to several
reasons. For example, a not valid XML syntax or simply a user oversight.
>
> It was failing with
>
>> undefined method 'fetch' for nil:NilClass"
Because the `Profile.current` had a `nil` value for the `software` key.
Use `hsh["key"] || default_value` instead `hsh.fetch("key", default_value)`.
Also added a `log.info` to easy the debugging process.
Added an expectation to the current test.

Avoid to crash when profile has a not valid sofware section

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/storage_proposal.rb
src/modules/AutoinstStorage.rb
test/autoinst_storage_test.rb

An error is reported when trying to install over a diskless system. But in case of root over NFS, the installation could still be performed (even when the system has no physical disks at all).
Current error should not appear when the profile indicates root over NFS.
* Needed for: https://bugzilla.suse.com/show_bug.cgi?id=1130256
* PBI: https://trello.com/c/x4LYDnwe/865-3-l3-important-bug-1130256-autoyast-for-a-nfs-root-fails-at-partitioning
* Related PR: https://github.com/yast/yast-storage-ng/pull/884
Remove current check completely, so only proposal issues will be shown when a proposal is not possible.
* Added unit tests
* Tested manually

Remove available devices check

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup_upgrade.rb

...when upgrading from SLES12 + SUMA Proxy + SUMA Branch Server
- Similar to https://github.com/yast/yast-update/pull/124, just for the AutoYaST autoupgrade
- 4.1.6

Uninstall the "SUSE-Manager-Proxy" product (bsc#1133215)

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb

[AutoYaST pre-scripts](https://www.suse.com/documentation/sles-15/singlehtml/book_autoyast/book_autoyast.html#createprofile.scripts) can modify the storage configuration/layout. For example, a script might create new partitions.
A storage-reprobing is done after running the pre-scripts, but only if any pre-script modifies the control file, or there are Dasd or zfcp devices. As result, in some cases the storage changes performed by the pre-scripts are not reflected in the devicegraph tree.
* https://bugzilla.suse.com/show_bug.cgi?id=1133045
* https://trello.com/c/3re8LvvF/1049-autoyast-hw-probing-behavior-vs-scripts
* Related cards:
* https://trello.com/c/fcaAfYJQ/944-3-l3-autoyast-installation-fails-with-error-during-the-create-partition-plans-phase
* …

Re-probe storage devices

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstRAID.rb
src/modules/AutoinstStorage.rb
test/AutoinstStorage_test.rb

When installing root over a Software RAID, snapper is not configured.
This is not a bug exactly, but a missing feature. The `AutoinstRAID` module has no support for enabling snapper.
* https://trello.com/c/JrY23Q8q/1090-3-sles12-sp34-1135083-snapper-does-not-get-setup-via-autoyast-for-btrfs-root-on-mdraid1
* https://bugzilla.suse.com/show_bug.cgi?id=1135083
Added support for enabling snapper when installing over a Software RAID.
* Manually tested
* Added unit tests
<details>
<summary>Click to show/hide</summary>
</details>

Allow to enable snappots when installing on Software RAID

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1140339
- https://trello.com/c/KKCZS798
I have tested the fix manually.
The bug was in not knowing what form a *name* should take. Whenever something has the `String` type, things can go wrong.

Fix autoyast_mini in openQA (bsc#1140339)

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/partitioning.rnc

Partially fixes [boo#1144007](https://bugzilla.suse.com/show_bug.cgi?id=1144007).
This change could be backported to SLE-15-GA and SLE-15-SP1.

Add missing 'uuid' element

---

doc/multipath.md

See https://trello.com/c/gAJZHQuD/
The behavior of AutoYaST with multipath has been an historical source of confusion and bug reports. This pull request provides a document explaining how the different values in the profile interact during the import process.

Document multipath behavior in SLE-12-SP4

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstLVM.rb

See https://bugzilla.suse.com/show_bug.cgi?id=1148918. AutoYaST is trying to reduce the size of the thin LVs to make them fit into the size of the physical disk where the LVM thin pool is located. That's exactly the opposed of the thin provisioning idea, in which LVs can be "over-committed"
Manually tested by @dgdavid 
Unit tests not added because the whole `AutoinstLVM` module is untested.
<details>
<summary>Click to show/hide screenshots</summary>
---
<p align="center">Before</p>
---
<p align="center">After</p>
</details>

Do not reduce thin LVs to disk size (bug#1148918)

---

package/autoyast2.changes
package/autoyast2.spec

When creating #522 I didn't realize SP4 and SP5 had diverged already and there was already a different 3.2.37 in SLE-15-SP5.

Fix version number. 3.2.37 already exists in SLE-12-SP5

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/autosetup_helpers.rb
test/lib/autosetup_helpers_test.rb

- Do not run registration again in the 2nd stage, running it in the 1st stage is enough :wink:
- https://bugzilla.suse.com/show_bug.cgi?id=1153293
- Tested manually with the AY profile attached in bugzilla
- Before applying the fix the registration was called again in the 2nd stage
- After applying the fix it was called only once in the 1st stage
- Added an unit test for this
- 4.2.11

Do not run the registration step twice (bsc#1153293)

---

test/Makefile.am

- Some tests were not specified in the `Makefile.am` and thus not run during `make check` which is run during RPM build.

Run all unit tests in "make check"

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoinit.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1154988
- Do not crash when using the online medium without the registration section in the AY XML profile
- Display an error message with some hints.
- 4.2.13
The original crash:
With the fix applied:
After pressing *OK* the installation aborts.

Display error when using the online medium without registration (bsc#1154988)

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/ayast_setup.rb
src/lib/autoinstall/clients/ayast_setup.rb
test/lib/clients/ayast_setup_test.rb

I've moved the active part of ayast_setup into an library which can be imported from other yast modules too.

Fix bsc#1154855 - During firstboot ayast_setup will not be executed.

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb
src/modules/AutoinstSoftware.rb
src/modules/Y2ModuleConfig.rb
test/Y2ModuleConfig_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1153746
- https://trello.com/c/g5Ss3rRS
AutoYaST in second stage shows a warning dialog saying it can't work on some sections of the AutoYaST profile because some packages should have been installed for this. (The screenshot in the Trello board shows sections `mail` and `kdump`.)
The package calculation got broken along with the 'org.opensuse' namespace move in our desktop files. As the files are named in camel-case, this is terminally broken and should be re-thought. But not as part of this pr.
Also, it seems `kdump` is not needed in 2nd stage at all.
3 parts:
- fix the function that determines the needed packages
- remove `kdump` from 2nd stage profile as the config is done in 1st stage
- `yast2-schema` package is needed in inst-sys; this is …

fix auto-adding required packages for autoyast sections (bsc#1153746)

---

src/Makefile.am

The last changes has no effect because of the missed file after installation.

Adapt Makefile

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_store_upgrade_software.rb
src/clients/software_auto.rb
src/modules/AutoinstSoftware.rb

Replacing old Pkg.ResolvableProperties()and Pkg.ResolvabeDependencies() calls by Y2Packager::Resolvable.any? and Y2Packager::Resolvable.find in order to save memory.

reducing memory usage

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/autopart.rb

If the extended partition already exists, the `extended_possible` key is set to `false`, thus the free partitions within the extended one were not taken into account.
It partially fixes https://bugzilla.suse.com/show_bug.cgi?id=1156567.

Count extended partition when determining if partitions fit

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/general_dialogs.rb

https://bugzilla.suse.com/show_bug.cgi?id=1084015
This puts en_US "translations" which are really fixes for broken English or broken translations back into the sources.
```po
#
msgid ""
msgstr ""
"Project-Id-Version: xPACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-12-20 02:28+0000\n"
"PO-Revision-Date: 2007-08-14 15:56+0200\n"
"Last-Translator: xFULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: xLANGUAGE <LL@li.org>\n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit"
#: src/include/autoinstall/general_dialogs.rb:120
msgid "Accept Non Trusted GPG Keys"
msgstr "Accept Untrusted GPG Keys"
#: src/include/autoinstall/general_dialogs.rb:274
msgid "Frametitle"
msgstr "Frame Title"
```

Fixed user-visible messages (bsc#1084015)

---

package/autoyast2.changes
package/autoyast2.spec
scripts/autoyast-initscripts.service

**Problem**
autoyast-initscripts.service is waiting for running network by the "old" target "network.target".
Newer version of systemd are supporting "network-online.target" which actively waits until the network is "up". See:
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
**Solution**
Replace the old target by the newer one.
**Test**
manually

Init script: Checking working network with network-online.target

---

Dockerfile

- Fixes Travis build
- Use `--force-resolution` zypper option to allow package downgrades to resolve package dependencies.

Travis fix

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstSoftware.rb

https://github.com/yast/yast-storage-ng/pull/1060 implements a long overdue refactoring of how yast2-storage-ng manages the so-called storage features and its related packages.
Now the API of `PackageHandler` and friends is properly object-oriented, SOLID and all that. But since it changed, this adaptation was needed in yast-autoinstallation (the only user of those classes outside yast2-storage-ng itself).

Package handler

---

modconfig/partitioning.desktop
modconfig/software.desktop
package/autoyast2.changes
package/autoyast2.spec

Some time ago, the icons used by YaST modules were updated and moved[1][2]. However, there are some missing icons in AutoYaST onfiguration, some of them completely deleted and others not properly updated in the _autoinstall_ desktop files.
* https://bugzilla.suse.com/show_bug.cgi?id=1168123
Only two of those icons can be fixed from here, using the right name. Additionally, the Partitioner group and categories has been updated too, to sync it with [3].
---
[1] https://github.com/yast/yast-theme/pull/100
[2] https://github.com/yast/yast-theme/commit/afa341066b9851808fbaa25756470cd119d41bfd
[3] https://github.com/yast/yast-storage-ng/blob/adb3e9b28cf6496f4440f7f2c0c78ab945266189/src/desktop/org.opensuse.yast.Disk.desktop

Fix (some) desktop files

---

Dockerfile
package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstPartPlan.rb
test/AutoinstPartPlan_test.rb

**Revert fix:**
---------------------------------------------------------------------------------------------------------
Mon Aug 12 10:48:18 CEST 2016 - schubi@suse.de
Cloning devices: Devices which are not needed for the
installation will be ignored explicitly in the "skip_list".
(bnc#989392)
3.1.146
The fix
https://github.com/yast/yast-autoinstallation/pull/240/files
is generating a wrong skip list.
The regarding bug
https://bugzilla.suse.com/show_bug.cgi?id=989392
Has two fixes. The first (248) one has not fixed the issue but has looked
good in general for potential other issues. But it does not behave as expected.
--> removing this fix is worth for it because it is used while calling
"yast clone_system"

Sle 12 sp4 bsc 1167596

---

package/autoyast2.changes
package/autoyast2.spec
src/Makefile.am

Recently, some missing icons were restored (see #585) but the _Makefile_ was not updated with those changes. So, the icons are not available in the final package.
This PR solves the problem.
Related to 
* https://bugzilla.suse.com/show_bug.cgi?id=1168123
* https://bugzilla.opensuse.org/show_bug.cgi?id=1168281
<details>
<summary>Click to show/hide the screenshot</summary>
---
| Icons properly shown in SLE-15-SP1 after apply those changes |
|-|
| ![Screenshot_sle15-sp1_2020-04-14_13:06:05](https://user-images.githubusercontent.com/1691872/79223635-9d9d3d80-7e51-11ea-8fc2-14e2b0d6fc22.png) |
</details>

[SLE-15-SP1] Fix the Makefile

---

src/lib/autoinstall/storage_controller.rb
src/lib/autoinstall/widgets/storage/add_children_button.rb
src/lib/autoinstall/widgets/storage/add_drive_button.rb
src/lib/autoinstall/widgets/storage/chunk_size.rb
src/lib/autoinstall/widgets/storage/disk_page.rb
src/lib/autoinstall/widgets/storage/filesystem.rb
src/lib/autoinstall/widgets/storage/filesystem_attrs.rb
src/lib/autoinstall/widgets/storage/format_filesystem.rb
src/lib/autoinstall/widgets/storage/md_level.rb
src/lib/autoinstall/widgets/storage/overview_tree_pager.rb
src/lib/autoinstall/widgets/storage/parity_algorithm.rb
src/lib/autoinstall/widgets/storage/partition_page.rb
src/lib/autoinstall/widgets/storage/partition_table.rb
src/lib/autoinstall/widgets/storage/raid_attrs.rb
src/lib/autoinstall/widgets/storage/raid_name.rb
src/lib/autoinstall/widgets/storage/raid_page.rb
src/lib/autoinstall/widgets/storage/used_as.rb
test/lib/storage_controller_test.rb
test/lib/widgets/storage/add_drive_button_test.rb
test/lib/widgets/storage/chunk_size_test.rb
test/lib/widgets/storage/filesystem_attrs_test.rb
test/lib/widgets/storage/filesystem_test.rb
test/lib/widgets/storage/format_filesystem_test.rb
test/lib/widgets/storage/md_level_test.rb
test/lib/widgets/storage/overview_tree_pager_test.rb
test/lib/widgets/storage/parity_algorithm_test.rb
test/lib/widgets/storage/partition_page_test.rb
test/lib/widgets/storage/raid_attrs_test.rb
test/lib/widgets/storage/raid_page_test.rb
test/lib/widgets/storage/used_as_test.rb

Among other fixes and improvements, this PR adds support to define and edit RAID devices.
* Extends the edition of partition sections so the user can decide how the partition is going to be used. For the time being, only *File system* and *RAID member* are available.
* Adds support to add a drive section with type `:CT_RAID`.

Add support for RAID definitions

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1170082
- https://trello.com/c/qC09yxJf
Autoinstallation doesn't see the activated iSCSI disks on the client because no re-probing of the storage data is triggered.
Backport https://github.com/yast/yast-autoinstallation/pull/511 to SLE-15-SP1.

Always re-probe storage after pre-scripts (bsc#1170082, bsc#1133045)

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/ayast_setup.rb
test/lib/clients/ayast_setup_test.rb

When ayast_setup is called without a `networking` section it modifies the profile adding it with the `keep_install_network => true` option. Thus, lan_auto client is called in order to write the configuration which crashes because there is no config imported to write (a problem with Modified detection)
- https://bugzilla.suse.com/show_bug.cgi?id=1170821
Remove the addition of the section when it is not defined as the Network should not be removed anymore since keeping the installed network is the default option (see https://github.com/yast/yast-autoinstallation/pull/221)
- Added unit test
Using the same profile, with only a user to be added:
```xml
<users config:type="list">
<user>
<username>yast</username>
...
</user>
</users>
```
And calling `yast2 ayast_setup setup …

ayast_setup: Do not add networking section when not defined explicitly

---

src/lib/autoinstall/presenters/partition.rb
src/lib/autoinstall/storage_controller.rb
src/lib/autoinstall/widgets/storage/delete_section_button.rb
src/lib/autoinstall/widgets/storage/disk_page.rb
src/lib/autoinstall/widgets/storage/disklabel.rb
src/lib/autoinstall/widgets/storage/not_lvm_partition_attrs.rb
src/lib/autoinstall/widgets/storage/overview_tree_pager.rb
src/lib/autoinstall/widgets/storage/partition_general_tab.rb
src/lib/autoinstall/widgets/storage/partition_id.rb
src/lib/autoinstall/widgets/storage/partition_tab.rb
src/lib/autoinstall/widgets/storage/partition_type.rb
src/lib/autoinstall/widgets/storage/partition_usage_tab.rb
src/lib/autoinstall/widgets/storage/uuid.rb
test/lib/presenters/partition_test.rb
test/lib/storage_controller_test.rb
test/lib/widgets/storage/delete_section_button_test.rb
test/lib/widgets/storage/disk_page_test.rb
test/lib/widgets/storage/disklabel_test.rb
test/lib/widgets/storage/overview_tree_pager_test.rb
test/lib/widgets/storage/partition_general_tab_test.rb
test/lib/widgets/storage/partition_id_test.rb
test/lib/widgets/storage/partition_tab_test.rb
test/lib/widgets/storage/partition_type_test.rb
test/lib/widgets/storage/partition_usage_tab_test.rb
test/lib/widgets/storage/shared_examples.rb

One step more in the path to `The New AutoYaST Storage UI` (see #592).
According to what was discussed offline, this PR 
* Move the encryption attributes to the _General_ tab
* Change some attributes labels (namely, _Partition UUID_ is now _UUID_ and _Partition table_ is _Disklabel_)
* Display _Partition Id_ and _Partition Type_ attributes unless the partition belongs to a LVM drive section
* Add a button to remove currently selected section (except if it is the only drive section available)
And also reorganize a bit the partition tabs code using a base class in an attempt to reduce the code duplication.
|||
|-|-|
| ![Screenshot_openSUSE-IceWM_2020-05-19_16:06:46](https://user-images.githubusercontent.com/1691872/82343500-d8fbd080-99ea-11ea-81b7-6dd09cf346e1.png) | ![Screenshot from …

[Storage UI] Fine tuning the interface

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb
src/clients/inst_autosetup.rb
src/lib/autoinstall/autosetup_helpers.rb
src/lib/autoinstall/clients/inst_autoinit.rb
src/modules/AutoinstConfig.rb
test/lib/autosetup_helpers_test.rb

Historically, AutoYaST has been divided in two stages, doing the installation during the first stage and the configuration during the second.
We have been moving some of the logic to the first stage, but it was still not the default and was only the default when there was no second stage defined.
- https://trello.com/c/s0QL7jvT/1840-8-move-network-configuration-to-1st-stage
Consider the first stage as the default stage for configuring the network. That is, if the `networking` section is defined in the profile, it will be imported, merging it with the current network config (linuxrc) unless it is specified to not keep the current config (**keep_install_network** option is defined in the profile as **false**)
From here, there are different options that could happen:
1. Setup the network …

Move network configuration to the 1st stage by default

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstClone.rb
src/modules/AutoinstGeneral.rb
test/AutoinstGeneral_test.rb
test/autoinst_clone_test.rb
test/profile_test.rb

The main point of this PR is to stop proposing insecure signature handling settings when cloning (see [bsc#1171343](https://bugzilla.suse.com/show_bug.cgi?id=1171343)). The problem does not affect the installation itself and I think it is a safe change to be included in SP2.
When I was about to add unit tests for this change, I realized that we already had some tests for the `AutoinstClone` module in `master`. So I decided to backport them and I included the fix to not export storage settings unless it is needed too (see [bsc#1171356](https://bugzilla.suse.com/show_bug.cgi?id=1171356)).
Finally, I have added a few tests to cover the import of the signature handling settings and then I realized that we were setting the wrong callback when importing `accept_unknown_digest`.
Trello: …

Do not propose insecure signature handling settings

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstClone.rb
src/modules/AutoinstGeneral.rb
test/AutoinstGeneral_test.rb
test/autoinst_clone_test.rb

Merges #618 into `master`. Additionally, it includes:
* Code clean-up for `AutoinstGeneral`.
* A minor fix to not call `SetSignatureHandling` twice.
* Drop the unused `@Confirm` variable.

bsc#1171343: do not propose insecure signature handling settings

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb
src/lib/autoinstall/autosetup_helpers.rb
src/lib/autoinstall/clients/inst_autoinit.rb
test/lib/autosetup_helpers_test.rb
test/lib/clients/inst_autoinit_test.rb

Since **SLE-15-SP2**, there is an **Online** Media which needs to register the system in order to add the repositories from **SCC**. This registration is done a step earlier than it is done with the Full media and was added by [this](https://github.com/yast/yast-autoinstallation/pull/530) PR.
In order to register the system, a network configuration is needed and it is usually configured by linurxc as you can see in the example below:
> **Linuxrc Options:** `ifcfg=eth0=dhcp autoyast=http://192.1681.122.1/control-files/minimal.xml`
But it is not the only way to configure the network. 
In cases where the network is very complex, or just because we have it already defined in a profile we can configure it through AutoYaST. There is an special flag for configuring it before the registration …

Move network configuration to autoinit client in case of online medium

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/common.rnc
src/autoyast-rnc/partitioning.rnc

- Work around Relax-NG parser error: "Found anyName attribute    without oneOrMore ancestor" ([bsc#1172131](https://bugzilla.opensuse.org/show_bug.cgi?id=1172131)) (companion to https://github.com/yast/yast-installation-control/pull/98)
- Rename 'option' to 'fs_option' to fix a duplicate definition    ([bsc#1170886](https://bugzilla.suse.com/show_bug.cgi?id=1170886))

Correct schema

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstGeneral.rb

Accidentally, we set the SetRebootAfterFirstStage method as private, but it is used from outside AutoinstGeneral.
See [bsc#1172865](https://bugzilla.opensuse.org/show_bug.cgi?id=1172865).

[bsc#1172865] SetRebootAfterFirstStage is not private anymore

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/xml.rb

As a user I would like to disable the update of the ntp servers through netconfig. That is, I would like to set the netconfig NTP_POLICY as "" (disable) in the AutoYaST profile ntp section.
The problem is that the ntp_policy attribute is empty and it is omitted when serializing the profile at the end of the first stage.
- https://bugzilla.suse.com/show_bug.cgi?id=1172026
Export ntp_policy via CDATA so that empty strings are preserved for the second stage.
Maybe we should do the same with other netconfig policy options.

Permit to use CDATA in the ntp_policy attribute

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/Profile.rb
test/profile_test.rb

Some AutoYaST modules are responsible for generating different parts of the profile. For instance, `yast2-users` generates the content of `<users>`, `<groups>`, `<login_settings>` and `<user_defaults>` sections. A side effect of the merging process is that, even if some of the exported sections is nil, it will appear in the final profile.
So, for instance, you will always have a `<login_settings>` section, even if it is empty. This PR fixes this issue.

Do not export useless sections

---

doc/validation.md
package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/conftree.rb
src/lib/autoinstall/autosetup_helpers.rb
src/lib/autoinstall/clients/inst_autoinit.rb
src/lib/autoinstall/xml_checks.rb
src/lib/autoinstall/xml_validator.rb
src/modules/AutoInstallRules.rb
src/modules/AutoinstClass.rb
src/modules/Profile.rb
src/modules/ProfileLocation.rb
test/AutoInstallRules_test.rb
test/AutoinstClass_test.rb
test/lib/autosetup_helpers_test.rb
test/lib/xml_checks_test.rb
test/lib/xml_validator_test.rb

It would be nice to check whether the given profile is valid or not while running AutoYaST. Now that we have an API that allows for that, we should integrate it into the installer.
- [Trello card](https://trello.com/c/nNTAyFqA)
- [Bugzilla bug](https://bugzilla.suse.com/show_bug.cgi?id=1173091)
The XML YaST module now supports XML validation via the nokogiri backend.
To make the code better structured I created two helper classes: generic `XmlValidator` which validates a XML file against a schema (without UI) and `XmlChecks` which uses the validator and check the AutoYaST files against the AutoYaST schema (displays an error popup when validation fails).
Because now the validation is mandatory and it already happened that we had a bug in the schema it should be possible to easily disable …

Profile Validation During Installation

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/clone_system.rb
src/modules/AutoinstClone.rb
src/modules/Profile.rb
test/autoinst_clone_test.rb
test/lib/clients/clone_system_test.rb
test/profile_test.rb

Allow the users to select how much information is exported by setting an additional `target` argument. For instance, the following command would instruct the modules to do not export *all* the information.
```
yast2 clone_system modules target=compact
```
Obviously, each module is responsible to select how much information it exports and it is expected that just a few modules implement support for this. Let's see some ideas:
* `yast2-users`: do not export non-system users (see https://github.com/yast/yast-users/pull/232).
* `yast2-network`: do not export `localhost` entries as part of the `<hosts>` section.
* `yast2-services-manager`: do not export services that have not changed.
* `yast2-firewall`: do not export empty zones.
https://github.com/yast/yast-yast2/pull/1067 implements support …

Reduce profile size on-demand

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb
src/lib/autoinstall/autosetup_helpers.rb
test/lib/autosetup_helpers_test.rb
test/test_helper.rb

During an AutoYaST installation, the country settings (language, keyboard, timezone) are already applied during the 1st stage and also during the second stage when it is run. In order to not process the configuration a second time the related sections should be removed during the first stage once imported.
- https://trello.com/c/VPtx0SyN/1921-3-move-keyboard-language-timezone-to-1st-stage
- Remove country related sections once imported during the 1st stage.
- Unit test added
- Tested manually with last staging J build (including last yast2-country changes https://github.com/yast/yast-country/pull/254)

Remove language, keyboard and timezone sections

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/reporting.rnc

When the report section is defined it expects all the schema elements to be given although AutoYaST already proposes default values when missing. Thus, the installation validation schema (https://github.com/yast/yast-autoinstallation/pull/624) reports an error which seems too strict.
https://trello.com/c/m3hv8ihn/1923-ostumbleweed-p2-1173312-schema-validation-seems-overly-strict
- Make the report section elements and theirs descendants optional.

AutoYaST schema: Make the report section elements optional

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb

Since https://bugzilla.suse.com/show_bug.cgi?id=1170821, the networking section is not added by default to the profile, in order to not call the auto client when not specifically needed.
The problem is that we remove the interfaces configuration when it is not defined in the profile.
- https://bugzilla.suse.com/show_bug.cgi?id=1173793
- The network interfaces configuration will not be removed by inst_autoconfigure anymore (backported partially from master see https://github.com/yast/yast-autoinstallation/pull/606/files#diff-b2063d649bd3696f9fefc54a84912ff7L131)
Decide if we would like to allow a way to delete existing network interfaces configuration and related files (routes, aliases entries etc)

Do not remove interfaces configuration when network section is absent

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/partitioning.rnc

As reported in https://bugzilla.suse.com/show_bug.cgi?id=1174071, the AutoYaST profile validation started failing with `ERROR: Element profile failed to validate content`.
<details>
<summary>Click to show/hide an screenshot</summary>
<p>
</p>
</details>
This happens because `partition` elements in the `autoinst.xml` profile have the `t="map"` attribute but it is currently missing in the schema.
To update the `partitioning.rnc` file, setting the `MAP` type to the `partition` element.
* Build both packages, yast-autoinstallation and yast-schema using the `--keep-pkgs` and `--prefer-pkgs` osc options
> **rake "osc:build[-p /tmp/pkgs -k /tmp/pkgs]"**
* Create a driver update
* Run the installation using the driver udpate and AutoYaST profile
The profile validations works fine and the auto …

Fix the type used for 'partition' elements

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/entries/description.rb
test/lib/entries/description_test.rb

trello: https://trello.com/c/bev3V41K/1966-2-tw-1174119-network-section-will-not-be-created-while-calling-yast-clonesystem

Fix client default name

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/autosetup_helpers.rb
test/lib/autosetup_helpers_test.rb

It fixes [bsc#1174118](https://bugzilla.suse.com/show_bug.cgi?id=1174118), which was a side effect of moving all the network configuration to the 1st stage. Additionally, it tries to simplify the `autosetup_network` method a bit.

[bsc#1174118] Do not crash when the networking section is missing

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/package_searcher.rb
test/lib/clients/inst_autosetup_upgrade_test.rb
test/lib/package_searcher_test.rb

- Filter the packages directly on the lilbzypp level, that's much faster
- Related to https://github.com/yast/yast-pkg-bindings/pull/136
- Related to [bsc#1175317](https://bugzilla.suse.com/show_bug.cgi?id=1175317)
- Fixed unit test (do not change the current language), running the tests locally failed for me because of present translations
- 4.3.37

Speed up finding the "autoyast()" supplements (bsc#1175317)

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/y2erb.rb
src/modules/ProfileLocation.rb
test/lib/y2erb_test.rb

trello: https://trello.com/c/gNgOHmh3/2016-5-dynamic-profiles-poc
how it works? Just pass erb file as autoyast parameter e.g. autoyast=ftp://neser-vr.suse.cz/dynamic.erb
and here is content of testing erb
```erb
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
<%# example how to dynamic force multipath. Here it use storage model and if
it contain case insensitive word multipath %>
<% if hardware["storage"].any? { |s| s["model"] =~ /multipath/i } %>
<general>
<storage>
<start_multipath t="boolean">true</start_multipath>
</storage>
</general>
<% end %>
<software>
<products config:type="list">
<product>openSUSE</product>
</products>
</software>
<%# for details about values see libhd  TODO: better API? %>
<% disks = hardware["disk"].sort_by { …
```

Erb template

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstGeneral.rb

when no type is defined explicitly, then string is assumed
For now this is expected to be a problem when signature_handling is empty and type definition is omitted completely. It for some reason has happened in bnc#1174133 when generating a profile, this fix should solve this issue. It intentionally do not handle incorrect explicit type definitions.
Profile export has also been checked with this version of autoyast and it correctly exports ```t="map"``` in signature_handling

Fixed internal error crash when signature_handling contains no type definition

---

.rubocop.yml
package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/ask.rb
src/modules/Profile.rb
test/profile_test.rb

Use the ElementPath object, introduced in https://github.com/yast/yast-yast2/pull/1090:
* Replace `setElementByTest` with  `set_element_by_path` which accepts a proper `ElementPath` object instead of an array.
* Use `ElementPath#from_string` in order to parse the ask-list path.

Use ElementPath class

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/xml.rb

Backport of https://github.com/yast/yast-autoinstallation/pull/676. It will not trigger the same error, but it can affect any user that uses the AutoYaST UI to generate a `postpartitioning-scripts` section.

bsc#1175714: export postpartitioning-scripts section properly

---

package/autoyast2.changes
src/lib/autoinstall/y2erb.rb
test/lib/y2erb_test.rb

trello: https://trello.com/c/zHOebVq5/2036-5-research-extend-dynamic-profile-helpers
new profile that works ( for old see https://github.com/yast/yast-autoinstallation/pull/667 ) :+1: 
```erb
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
<%# example how to dynamic force multipath. Here it use storage model and if
it contain case insensitive word multipath %>
<% if hardware["storage"].any? { |s| s["model"] =~ /multipath/i } %>
<general>
<storage>
<start_multipath t="boolean">true</start_multipath>
</storage>
</general>
<% end %>
<software>
<products config:type="list">
<product>openSUSE</product>
</products>
</software>
<%# first lets create list of disk names according to its size %>
<% sorted_disks = disks.sort_by { |d| d[:size] }.map { …
```

add helper for enumerate disks

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb
src/modules/AutoinstSoftware.rb
test/AutoinstSoftware_test.rb

If the NetworkManager package is not added explicitly into the software section then it is not enabled correctly during the first_stage switching to wicked as the network service.
In the second stage, it does not try to switch between backends and the check of needed packages is based in the current service which is wrong according to the profile.
- https://trello.com/c/yeV9lOmS/2025-3-sled15-sp2-p3-1172817-networkmanager-not-getting-installed-via-autoyast-sled-15-sp2-rc3
Add the package to the list of packages to be installed when 'NetworkManager' is selected as the network backend to be used.

Add NetworkManager package when missing in software but needed

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstPartPlan.rb
test/AutoinstPartPlan_test.rb

[boo#1176490](https://bugzilla.opensuse.org/show_bug.cgi?id=1176490). Basically, `AuitoinstPartPlan.Read` should return a ycp-compatible type.
Trello: https://trello.com/c/sSED0daZ/4281-drop-autoinstdrive-autoinstpartition-and-friends

Fix storage reading

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/partitioning.rnc

The AutoYaST profile validation started failing because the missing `MAP` attribute in the schema for the `bcache_options` element.
* https://bugzilla.suse.com/show_bug.cgi?id=1176595
To update the `partitioning.rnc` file, setting the `MAP` type to the `bcache_options` element. 
Tested manually - runing the xmllint validation locally - following steps described in https://github.com/yast/yast-autoinstallation/pull/650

Add missing MAP type to bcache_options element

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autoinit.rb
test/lib/clients/inst_autoinit_test.rb

The import of the general and report configuration happens before the `pre-scripts` handling. Thus, the signature handling and report default configuration is not imported correctly if not defined in the `pre-script` xml.
In the bug in particular, it complains when a repository is added and it is not digitally signed.
- https://trello.com/c/zkB79isR/2057-3-sles15-sp2-p5-1175725-even-when-setting-insecure1-there-is-an-error-that-the-repomdxml-is-not-digitally-signed
Import both configurations ('report' and 'general') if the profile is modified by pre-scripts.
- Tested manually with a pre-script without signature handling section which fetches the complete profile:

Reimport general and report sections in case of pre-script modified profile

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autoinit.rb
src/modules/AutoInstallRules.rb
test/lib/clients/inst_autoinit_test.rb

It merges #698 and fix a failing unit test because of missing initialization see https://github.com/yast/yast-autoinstallation/pull/694#issuecomment-693300881.

Merge SLE-15-SP2 into 'master' and fixed AutoIntallRules unit test

---

src/modules/AutoInstallRules.rb

It fixes the submit to IBS as the used method is not supported in ruby-2.5 see https://ci.suse.de/job/yast-yast-autoinstallation-master/69/console

Fix IBS build using Builtin.union instead of unsupported Array#union

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoinit.rb

Fix from #698 backported to GA as we did when moved the pre-scripts ASAP (related to https://github.com/yast/yast-autoinstallation/pull/638)

Import initial configuration from the profile when modified by pre-scripts

---

test/autoinst_clone_test.rb

The build of the package is failing in different architectures:
https://build.suse.de/package/live_build_log/Devel:YaST:SLE-15-SP2/autoyast2/SUSE_SLE-15-SP2_Update/aarch64
[   88s]      # Storage::LockException:
[   88s]      #   Storage::LockException
[   88s]      #   /usr/share/YaST2/lib/y2storage/storage_manager.rb:88:in `initialize'
Apparently we are not using the proper storage instance
Use a storage test instance for running the unit tests.

Fix tests to use correct storage instance

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/xml_checks.rb

Improve validation errors presentation. In Qt, the errors were looking good. However, the "details" header does not look good in textmode.

Improve libxml2 validation errors presentation

---

package/autoyast2.changes
package/autoyast2.spec
test/lib/clients/inst_autosetup_test.rb

Fix [bsc#1177227](https://bugzilla.suse.com/show_bug.cgi?id=1177227).

Fix inst_autosetup client tests

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb

- There was a conflict between `zzz_reboot` scripts [here](https://github.com/yast/yast-autoinstallation/blob/104c18f1a56d02ab50055cdf09653db964b97888/src/modules/Profile.rb#L157) and [here](https://github.com/yast/yast-autoinstallation/blob/39bc71d066b81ec6e3a6e73003f6bf45bc80b99f/src/clients/inst_autoconfigure.rb#L163)
- The AutoYaST reported an error [here](https://github.com/yast/yast-autoinstallation/blob/f71897c873392c0478312ef175495974dabbc8e6/src/modules/AutoinstScripts.rb#L147)
- 4.3.59

Resolve "zzz_reboot" script conflict (bsc#1177036)

---

package/autoyast2.changes
src/lib/autoinstall/clients/inst_autoinit.rb

Fixes [bsc#1177322](https://bugzilla.suse.com/show_bug.cgi?id=1177322).

bsc#1177322: progress bar length

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/backup.rnc
src/autoyast-rnc/upgrade.rnc

Another fix for [bsc#1176834](https://bugzilla.suse.com/show_bug.cgi?id=1176834) and [bsc#1176848](https://bugzilla.suse.com/show_bug.cgi?id=1176848).
See https://github.com/yast/yast-schema/pull/92 for `yast2-schema` counterpart.

bsc#1176834: allow setting the config:type for upgrade/backup

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/xml_checks.rb

We have received some complaints about the XML validation being annoying (e.g., see [bsc#1176973](https://bugzilla.suse.com/show_bug.cgi?id=1176973#c9)). We would like to keep it enabled by default, but we have decided to apply the same timeout that applies to any other AutoYaST warning (10 seconds by default).

XML validation timeout

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autoinit.rb
src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
src/modules/AutoinstFunctions.rb
test/lib/clients/inst_autosetup_upgrade_test.rb

Upgrade: Checking if a valid base product has been selected for upgrade and if not asking the user to check the product entry  in the AY configuration file (bsc#1175876)
Merge with https://github.com/yast/yast-autoinstallation/pull/724/files

Merge with SLES15-SP2

---

.github/workflows/ci.yml
package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/presenters/partition.rb
src/lib/autoinstall/widgets/storage/filesystem_attrs.rb
test/lib/widgets/storage/filesystem_attrs_test.rb
test/lib/widgets/storage/partition_usage_tab_test.rb

See [bsc#1181577](https://bugzilla.suse.com/show_bug.cgi?id=1181577).
In the partitioning section of the UI offered by YaST to customize an AutoYaST profile, the field "Mount Options" of the partition section was completely broken. It didn't show the value read from the system (or from the AutoYaST profile used as input) and it did not transfer the value written by the user to the resulting AutoYaST profile.
The root of the problem was using the attribute `Y2Storage::AutoinstProfile::PartitionSection#fstab_options` that operates with arrays of strings instead of a plain string with the attributes concatenated (separated by comma).
Since we work with the final concatenated string in the UI, do the following:
- When exporting to XML, use directly the field `fstopt`
- When initializing the …

AutoYaST UI: fix field fstopt in partitioning (bsc#1181577)

---

test/lib/clients/inst_autosetup_upgrade_test.rb

follow up of https://github.com/yast/yast-autoinstallation/pull/731 which failed in jenkins, so no version/changes needed.

fix missing product controls

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstSoftware.rb

This PR tries to address a problem detected while implementing support for SELinux. When SELinux is enabled, (Auto)YaST should select the `selinux` pattern (defined in the control file) for installation. In AutoYaST it only works when the installation summary screen is shown. Why? Because the software proposal runs and the pattern gets selected.
However, if the summary is skipped, the software proposal does not run and the pattern is ignored.
If you are wondering why it works in other cases (like `yast2-bootloader`), it is because they use *packages* instead of *patterns*.
We need to review the general workflow, but this patch should fix the problem for MicroOS. However, I would like to ask @lslezak if he can foresee any potential problems. An alternative could be something like:
```ruby …
```

Select patterns for installation

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstSoftware.rb
test/ProfileLocation_test.rb

Sync to master changes done at https://github.com/yast/yast-autoinstallation/pull/734
> [...] address a problem detected while implementing support for SELinux. When SELinux is enabled, (Auto)YaST should select the selinux pattern (defined in the control file) for installation. In AutoYaST it only works when the installation summary screen is shown. Why? Because the software proposal runs and the pattern gets selected.
> 
> However, if the summary is skipped, the software proposal does not run and the pattern is ignored.
> [...]

[SLE-15-SP3] Select patterns fort installation

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb

A bug report (https://bugzilla.suse.com/show_bug.cgi?id=1182543 ) got because of [SELinux proposal](https://github.com/yast/yast-security/pull/88) not working as expected during an auto-installation, revealed that security client was not being executed if the given profile does not contains a `security` section.
To solve the issue, below changes are needed:
* Always call the client, giving an empty hash when security section is absent (this PR)
* Ensure defined SELinux patterns are set when needed, done at https://github.com/yast/yast-security/pull/101
Tested manually via `yupdate` using `SUSE-MicroOS-5.0-DVD-x86_64-Build85.5` and also applying changes proposed at https://github.com/yast/yast-security/pull/101
<details>
<summary>Show/hide some excerpts from YaST logs</summary>
---
```
... …
```

[SLE-15-SP2] Always import security settings

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autosetup.rb

Proposed fix for [bsc#1183042](https://bugzilla.suse.com/show_bug.cgi?id=1183042).

bsc#1183042: postpone importing security settings

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/rules.rnc

It removes a left-over from #683. Actually, it is `haspcmica` instead of `haspcmcia`.
See [bsc#1183352](https://bugzilla.suse.com/show_bug.cgi?id=1183352).

bsc#1183352: remove 'haspcmica' leftover

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/Profile.rb

The initialization of AY networking settings is scattered in different places and it is prone to errors or false expectations.
- https://trello.com/c/QV11z6q5/2332-p2-1180535-autoyastintel-udevadm-control-reload-failed
- Remove the initialization of the start_immediately element in the networking_section from the Profile.
It depends on https://github.com/yast/yast-network/pull/1180 as the default for start_immediately in yast2-network was false.

Network start immediately

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/pkg_gpg_check_handler.rb

- https://trello.com/c/YHXqyvAd
- https://bugzilla.suse.com/show_bug.cgi?id=1180968
An empty `<signature-handling>` element in an AutoYaST profile will crash YaST.
Empty elements in AutoYaST profiles are in some cases (not all) a problem due to the way XML is handled in YaST.
This pull request just fixes the reported issue. For a full analysis and a more general fix see https://github.com/yast/yast-autoinstallation/pull/730

fix handling of empty signature-handling element in autoyast profile (bsc#1180968)

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/conftree.rb

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1184216

Fix conftree crash

---

package/autoyast2.changes
src/autoyast-rnc/partitioning.rnc

* [bsc#1184268](https://bugzilla.suse.com/show_bug.cgi?id=1184268): add the `<mkfs_options>` to the `<partition>` section.
The version number is not incremented because I would like to merge more fixes before releasing version 4.3.77.

Add <mkfs_options> element to the <partition> section

---

package/autoyast2.changes
src/lib/autoinstall/clients/inst_autoinit.rb

This PR is an alternative approach to https://github.com/yast/yast-autoinstallation/pull/748 in order to fix [bsc#1184317](https://bugzilla.suse.com/show_bug.cgi?id=1184317). Instead of reverting changes, it makes sure that the `ask-list` is up-to-date. Alternatively, we could call [import_initial_config](https://github.com/yast/yast-autoinstallation/blob/d857aeac4aa70d71b9fe99f083b7f7042163a2f5/src/lib/autoinstall/clients/inst_autoinit.rb#L186), but it does more than needed.

 Show the ask-list only once (alternative approach)

---

package/autoyast2.changes
package/autoyast2.spec
src/include/autoinstall/conftree.rb
src/lib/autoinstall/entries/description_sorter.rb

AutoYaST crashes when it is processing the list of modules to run during the 2nd stage if the *yast2-audit-laf* package is installed. The problem has two sides:
* The `org.opensuse.yast.AuditLAF.desktop` file contains an entry `AutoInstRequires` that points to an non-existing `audit` module.
* AutoYaST is unable to handle this situation and it just crashes.
This PR introduces these changes:
* If a required module is missing, AutoYaST just logs the error and continues,
* The list of modules is written to the log file, so it is easier to find out a potential problem.

bsc#1184316: crash when sorting the list of modules

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1184508
AutoYaST profile processing may break in 2nd stage.
Fix profile reader.
This fixes the reported issue and makes AutoYaST installations possible again. There might be more places. The profile parsing code needs more refactoring time.

fix autoyast profile parser (bsc#1184508)

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/autosetup_helpers.rb
test/lib/autosetup_helpers_test.rb

During an autoupgrade, it tries to register the system even when in the profile it is set to not do so.
- https://trello.com/c/DHlfQO4m/2437-3-sles15-sp2-p5-1176965-was-l3-proxy-autoupgrade-scccredentials-force-connection-to-scc-which-causes-installation-to-fail
- https://bugzilla.suse.com/show_bug.cgi?id=1176965
Skip the registration in case it is explicitly disabled in the profile.

Autoupgrade: do not register the system if disabled explicitly in the profile

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
test/lib/clients/inst_autosetup_upgrade_test.rb

With this PR, AutoYaST will honor the packages registered in the `Yast::PackagesProposal` by the yast2-bootloader module.
Fixes [bsc#1184488](https://bugzilla.suse.com/show_bug.cgi?id=1184488).
Trello: https://trello.com/c/fZYFWGve/
Manually tested using QEMU.

Process PackagesProposal packages during autoupgrade

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/autoinst_files_finish.rb
src/clients/inst_autosetup.rb
src/lib/autoinstall/clients/autoinst_files_finish.rb
test/lib/clients/autoinst_files_finish_test.rb

Backport #651 to fix [bsc#1174194](https://bugzilla.suse.com/show_bug.cgi?id=1174194).
* Moving <files> section handling to the first installation stage.
* See https://github.com/yast/yast-installation/pull/954
* Trello: https://trello.com/c/jgBnBQOU/

Backport handling of <files> section in 1st stage

---

package/autoyast2.changes
package/autoyast2.spec

The **icewm** package was moved to the **basic_desktop** pattern (requested by https://jira.suse.com/browse/SLE-5558)
If the package and the pattern are not specified in the profile we could end with a graphical installation without a display manager which could be painful (see https://bugzilla.suse.com/show_bug.cgi?id=1185095).
A [similar bug](https://bugzilla.suse.com/show_bug.cgi?id=1165646) was already reported for **firstboot** and it was decided to recommend the **icewm** package in case that **libyui-qt** is installed as you can see here (https://github.com/yast/yast-firstboot/pull/96)
The pull request also contains a description of the problem and the solution applied so it could be just be applied for this PBI
- As the AutoYaST Second Stage is similar to Firstboot it has been …

Recommend icewm if libyui-qt is installed

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb
src/lib/autoinstall/clients/inst_autosetup.rb
src/lib/autoinstall/importer.rb
test/lib/clients/inst_autosetup_test.rb
test/lib/importer_test.rb

This PR is the counterpart of https://github.com/yast/yast-users/pull/296. Basically, it stops the autoinstallation when importing user settings fails.

Stop when importing users fails

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/autosetup_helpers.rb
test/lib/autosetup_helpers_test.rb

The proxy configuration is done during the second stage of the autoinstallation. As it could be very late and we have options for configuring the network before the proposal we probably could move it too.
- https://trello.com/c/s9gfK64m/2499-sles15-sp2-p2-1185016-l3-autoyast-does-not-set-proxy-properly-ref00d1iglod5001ixjkyhref
- https://bugzilla.suse.com/show_bug.cgi?id=1185016
Move proxy configuration to the first stage.
- Tested manually and added unit test.

Import proxy settings at the first stage

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstStorage.rb
test/autoinst_storage_test.rb

As described in [bsc#1187180](https://bugzilla.suse.com/show_bug.cgi?id=1187180), AutoYaST crashes with the following general section:
```xml
<general>
<storage></storage>
</general>
```

 Do not crash when the storage section is empty

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoInstall.rb
test/AutoInstall_test.rb

[bsc#1187221](https://bugzilla.opensuse.org/show_bug.cgi?id=1187221)
The copy of the profile to `/var/adm/autoinstall/cache/installedSystem.xml` got accidentally broken in https://github.com/yast/yast-autoinstallation/pull/754. This PR fixes the issue.

bsc#1187221: copy profile to installed system

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/scripts_auto.rb
test/lib/clients/scripts_auto_test.rb

[bsc#1187898](https://bugzilla.opensuse.org/show_bug.cgi?id=1187898)
Found by @joseivanlopez, the `scripts_auto` client crashes when it tries to import the list of scripts. To be clear, it does not affect the installation, because the import sequence is just different. This bug is another face of 
[bsc#1184508](https://bugzilla.opensuse.org/show_bug.cgi?id=1184508).

Do not crash while importing the <scripts> section

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb

This PR should fix [bsc#1187962](https://bugzilla.opensuse.org/show_bug.cgi?id=1187962). The type of the script is wrong, and it should be [`"init-scripts"`](https://github.com/yast/yast-autoinstallation/blob/master/src/lib/autoinstall/script.rb#L414-L416) instead of `"init"`.

bsc#1187962: properly register init-scripts to reboot after online update

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autoconfigure.rb

This PR brings [bsc#1187962](https://github.com/yast/yast-autoinstallation/pull/774) into `master`.

bsc#1187962: properly register init-scripts to reboot after online update (master)

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstGeneral.rb
test/AutoinstGeneral_test.rb

Do not export the general/storage section when it is empty (related to [bsc#1171356](https://bugzilla.suse.com/show_bug.cgi?id=1171356) and [bsc#1187916](https://bugzilla.suse.com/show_bug.cgi?id=1187916)).

Do not export empty general settings

---

src/lib/autoinstall/clients/autoyast.rb
src/modules/ProfileLocation.rb
test/ProfileLocation_test.rb
test/lib/clients/autoyast_test.rb

A new [check-profile](https://github.com/yast/yast-autoinstallation/pull/696) command was recently added. This command is intended to check an AutoYaST profile without applying changes to the system. Generally, such a check could be done without root permissions, but there are some situations where root permissions are required:
* With option *run-scripts=true*, if the script code requires root permissions.
* With an *ERB* profile, if the *ERB* code requires root permissions.
* With option *import-all=true*, if any of the imported modules requires probing.
Running scripts/ERB code as root could lead to security problems, see:
* https://gist.github.com/lslezak/26b6ceb1e340c7216106bd43c5748b86.
* https://bugzilla.suse.com/show_bug.cgi?id=1177123
It is difficult (or almost impossible) to …

Improving check-profile

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/rules.rnc

Fixes [bsc#1188153](https://bugzilla.suse.com/show_bug.cgi?id=1188153). The problem was reported against `SLE-15-SP3`, but it applies to `SP2` too. Additionally, I found another problem with the `installed_product*` elements, so I backported that fix too.

Fix rules schema

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstFile.rb
test/AutoinstGeneral_test.rb
test/autoinst_file_test.rb

Fixes [bsc#1188357](https://bugzilla.suse.com/show_bug.cgi?id=1188357)
This problem might affect SLE 15 SP2 once [this change](https://github.com/yast/yast-autoinstallation/blob/SLE-15-SP2/package/autoyast2.changes#L19-L21) reaches the installer update channel.
When using `file_location`, the file is copied to the inst-sys instead of the final system. The real issue is that `GetURL` is not aware of SCR changed root. However, as it is used in several places, I have decided to fix the problem in the caller, having the `Installation.destdir` into account. Additionally, I took the chance to add a few unit tests.
For this change to work, we need and up-to-date `yast2-installation` package (version `4.2.52` at least).

bsc#1188357: copy files to the right location when `file_location` is given

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/script.rb
test/lib/script_test.rb

Fixes [bsc#1188360](https://bugzilla.suse.com/show_bug.cgi?id=1188360).
init-scripts are always copied to the target, similar to [chrooted scripts](https://github.com/yast/yast-autoinstallation/blob/master/src/lib/autoinstall/script.rb#L388).

bsc#1188360: copy init-scripts to the target system

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/Profile.rb
test/profile_test.rb

- The problem happens when setting the `<final_reboot config:type="boolean">true</final_reboot>` option in the AutoYaST profile
- See https://bugzilla.suse.com/show_bug.cgi?id=1188356
- During debugging it turned out that the workflow is this:
- The `Import()` method in the `Profile` module does some processing, in this case it adds a custom reboot script when `final_reboot` is set to actually do the reboot
- The saved profile from the 1st stage to the 2nd stage contains both, the `final_reboot` flag and the custom script
- The `Import()` method is called again the 2nd stage, it does the same processing again and adds the second custom reboot script accidentally
- When AutoYaST runs the custom scripts later it complains that the same script is defined twice
- When inspecting the code the …

[SP3] Add "final_reboot" and "final_halt" scripts only once (bsc#1188356)

---

package/autoyast2.changes

* This reverts commit 932728f26166b0e3ebf4ddec8251e4b23d32a3d6.
* The changes were part of version 4.4.1, not 4.3.77.
* See https://github.com/yast/yast-autoinstallation/blob/master/package/autoyast2.changes#L116-L128

Revert "Added some missing SP3 changes"

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstScripts.rb
test/AutoinstScripts_test.rb

https://bugzilla.suse.com/show_bug.cgi?id=1188930
https://bugzilla.suse.com/show_bug.cgi?id=1188716
From SLE 15 SP3 on, AutoYaST user scripts that have a `<notification>` tag tend to cause a UI error pop-up _No widget with ID ..._. Removing the `<notification>` tag appears to fix the problem.
The pop-up with the notification gets in the way when the progress report in the main window is updated: Since the pop-up with the notification is still open, the widget with the requested ID (containing the progress) cannot be found, causing this error.
**Side note:** This is only a fatal error for certain UI built-ins like `UI.ReplaceWidget()`, not for others like `UI.ChangeWidget()`, but the error can also be observed in the y2log for those other UI built-ins, so it appears to happen quite often …

[SLE-15-SP3] Ensure Closing Script Notification Pop-ups

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/rules.rnc

* According to [bsc#1190696](https://bugzilla.suse.com/show_bug.cgi?id=1190696) this element is not validated properly.
* BTW, backport the fix to remove the `haspcmica` element ([bsc#1183352](https://bugzilla.suse.com/show_bug.cgi?id=1183352)).
Related to https://github.com/yast/yast-schema/pull/113.

Update rules.xml schema (bsc#1190696)

---

src/lib/autoinstall/clients/inst_autoinit.rb
src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
src/modules/AutoinstFunctions.rb
test/AutoinstFunctions_test.rb
test/lib/clients/inst_autosetup_upgrade_test.rb

Adapt the module to the new `ProductSpec` API. Additionally, it reorganizes the tests of `AutoinstFunctions.selected_base` in a more RSpec-like way.
* https://github.com/yast/yast-packager/pull/583
* https://github.com/yast/yast-yast2/pull/1199

Adapt to the ProductSpec API

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autoinit.rb

https://trello.com/c/nIoJgTXG/2615-3-sles15-sp3-p5-1188211-absence-of-product-in-autoyast-profile-causes-different-behavior-for-online-and-full-medium
in general stop autoinstallation on online medium if registration failed.

Fix empty product crash sp3

---

src/lib/autoinstall/clients/inst_autoinit.rb

fix for https://trello.com/c/nIoJgTXG/2615-3-sles15-sp3-p5-1188211-absence-of-product-in-autoyast-profile-causes-different-behavior-for-online-and-full-medium
sadly it is still shows a slighly different message, but we cannot now distinguish between reasons for failed registration.

abort install if reg failed and there is no repo

---

test/lib/autoinstall/widgets/ask/password_field_test.rb

Depending on the order, the tests may fail because "cwm/rspec" is not properly required.
See https://build.suse.de/package/live_build_log/Devel:YaST:Head/autoyast2/SUSE_SLE-15-SP4_GA/ppc64le.

Add missing require of "cwm/rspec"

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup.rb
test/lib/clients/inst_autosetup_test.rb

The `<add-on>` section is processed [during the 1st stage](https://github.com/yast/yast-autoinstallation/blob/a214818656d0ad4d8cd06b89a779e177b42c2d9a/src/lib/autoinstall/clients/inst_autosetup.rb#L135-L138). So AutoYaST does not need to process it again during the 2nd stage.
Although this section is never processed during the 2nd stage (because of the specification in the profile), it may ask the user to install yast2-add-on even if it is not going to be processed.
I will ask for review and merge after some tests.

bsc#1192185: Do not process the <add-on> section again

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup_upgrade.rb
test/lib/clients/inst_autosetup_upgrade_test.rb

During autoupgrade the Second Stage is basically ignore because there is no workflow defined in the [installation control file](https://github.com/yast/skelcd-control-SLES/blob/master/control/installation.SLES.xml#L391) and the workflow is not merged when the product is selected during the autoupgrade setup.
- https://trello.com/c/CfwIZXMK/2750-3-sles15-sp3-p2-1192437-l3-autoyast-post-installation-scripts-not-being-executed
Merge the workflow of the selected product as we [already do](https://github.com/yast/yast-autoinstallation/blob/master/src/lib/autoinstall/clients/inst_autosetup.rb#L121) during autosetup.

Merge product workflow during autosetup_upgrade

---

test/lib/efi_detector_test.rb

Fix for failing build:
```[  122s] Failures:
[  122s] 
[  122s]   1) Y2Autoinstallation::EFIDetector.boot_efi? when called in normal Mode returns true if '/sys/firmware/efi/efivars' exists
[  122s]      Failure/Error: expect(described_class.boot_efi?).to eq(true)
[  122s] 
[  122s]        expected: true
[  122s]             got: false
[  122s] 
[  122s]        (compared using ==)
[  122s] 
[  122s]        Diff:
[  122s]        @@ -1,2 +1,2 @@
[  122s]        -true
[  122s]        +false
[  122s]      # ./test/lib/efi_detector_test.rb:36:in `block (5 levels) in <top (required)>'
[  122s] 
[  122s]   2) Y2Autoinstallation::EFIDetector.boot_efi? when called in normal Mode returns true if '/sys/firmware/efi/vars/' exists
[  122s]      Failure/Error: expect(described_class.boot_efi?).to …
```

Fix unit test Stage mocking

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autoinit.rb
src/lib/autoinstall/clients/inst_autosetup_upgrade.rb

This PR tries to fix a side effect of #811. When a user tries to autoupgrade a system using the online medium, the product is not available at the beginning of the `inst_autosetup_upgrade` client, so `AutoinstFunctions.selected_product` returns `nil`.
The product will be available after calling `suse_register`, so it makes sense to merge the workflow at that point.
*Note: autoinstallation is not affected because the registration is almost the first step, so the packages are already available.*
* [bsc#1192437](https://bugzilla.suse.com/1192437)
* [bsc#1194440](https://bugzilla.suse.com/1194440)
* https://trello.com/c/hT3653E4/

Online autoupgrade workflow

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/pkg_gpg_check_handler.rb
src/modules/AutoInstall.rb
src/modules/AutoinstGeneral.rb
test/AutoInstall_test.rb
test/lib/pkg_gpg_check_handler_test.rb

Fixes [bsc#1194881](https://bugzilla.suse.com/show_bug.cgi?id=1194881). The problem was originally introduced in #809 because the `add-on` section was removed once it was read. However, the `PkgGpgCheckHandler` used the `Profile.current` content when checking the signatures (which is wrong).
Now, this class gets the general signature handling settings and the add-ons list, so it does not depend on the profile anymore.
Manually tested on SLE-15-SP3.

Fix addons signature handling

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup.rb
src/lib/autoinstall/clients/software_auto.rb
src/modules/AutoinstSoftware.rb
test/AutoinstSoftware_test.rb
test/lib/clients/software_auto_test.rb

Adapt AutoYaST to do not use the `PackageAI` module anymore. It should use the generic `Package` instead. See https://github.com/yast/yast-yast2/pull/1219.
**NOTE: tests are expected to fail until the https://github.com/yast/yast-yast2/pull/1219 is merged.**

Replace `PackageAI` with `Package` references

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/autosetup_helpers.rb
src/modules/Profile.rb
test/lib/autoinstall/ask/runner_test.rb
test/lib/autosetup_helpers_test.rb

* Trello: https://trello.com/c/3rHR1uFq
* [bsc#1195630](https://bugzilla.suse.com/show_bug.cgi?id=1195630)
When the path contains more than 1 level (for instance `network,dns,hostname`), the change is not applied (it is applied, but to a different `ProfileHash` instance). It works for simpler cases like `users,0,username`.
```ruby
{ "users" => [
{ "username" => "root" }
] }
{ "network" => {
"dns" => { "hostname" => "example" }
} }
```

bsc#1195630: properly update the profile when using the  `<ask-list>` mechanism

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/ayast_setup.rb
test/lib/clients/ayast_setup_test.rb

* [bsc#1195631](https://bugzilla.suse.com/show_bug.cgi?id=1195631)
* https://trello.com/c/u2PVCYsE/
`ayast_setup` does not import the `<general>` section. Although it is usually not a problem, it can affect `sap-installation-wizard`. So this PR makes `ayast_setup` client to import the general settings.
Additionally, it adapts the `ayast_setup` test to [bsc#1194886](https://bugzilla.suse.com/1194886).
**NOTE: the issue is still under investigation.**

bsc#1195631: ayast_setup imports general settings

---

package/autoyast2.changes
package/autoyast2.spec
xslt/merge.xslt

Port https://github.com/yast/yast-autoinstallation/pull/827 to SLE15-SP4/Factory.
- https://bugzilla.suse.com/show_bug.cgi?id=1195910
AutoYaST profile XSLT processing strips CDATA.
The processing happens when merging class-based profile bits here: https://github.com/yast/yast-autoinstallation/blob/SLE-15-SP3/src/modules/AutoInstallRules.rb#L873-L894
Our XSLT stylesheet will actually use CDATA for certain elements: https://github.com/yast/yast-autoinstallation/blob/master/xslt/merge.xslt#L15.
The problem is that AutoYaST profiles define a default namespace and the element matching fails.
Use the same default namespace in the XSLT stylesheet.

add yast namespace to merge.xslt to fix CDATA handling (bsc#1195910)

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstSoftware.rb
test/AutoinstSoftware_test.rb

Consider user-selected packages as optional to not block the installation. The problem was introduced when [we got rid of PackageAI](https://github.com/yast/yast-autoinstallation/pull/820/files), which kept a separate list of packages.
If we do not consider those packages as optional (which actually are), the installation [is blocked](https://github.com/yast/yast-packager/blob/bff0d8babd17eff9951554f4607707738298181e/src/modules/Packages.rb#L2551) when checking for missing packages.
* https://trello.com/c/qSCPq5EM/
* https://bugzilla.suse.com/1195747

bsc#1195747

---

package/autoyast2.changes
package/autoyast2.spec
scripts/autoyast-initscripts.service

When running *autoyast-initscripts.service*, the display manager or getty prompt is reached before scripts have finished.
* Related to https://bugzilla.suse.com/show_bug.cgi?id=1195059
* See also https://bugzilla.suse.com/show_bug.cgi?id=1195910#c45
Force *display-manager.service* and getty services to run after *autoyast-initscripts.service*.
See also https://github.com/yast/yast-installation/pull/1030.
Manually tested.

Avoid login 

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autopost.rb
src/modules/AutoInstall.rb
src/modules/AutoinstGeneral.rb
test/AutoinstGeneral_test.rb

`general/signature-handling` settings are ignored in the 2nd stage.
- https://bugzilla.suse.com/show_bug.cgi?id=1197655
- https://trello.com/c/iQWIXNnG/
**WIP: I will change the code to avoid this problem in the future again**
The [AutoinstGeneral](https://github.com/yast/yast-autoinstallation/blob/81f27da576fb263ae884d0a7835331753e8552b3/src/modules/AutoinstGeneral.rb#L461-L469) module reads the profile once is imported. That's quite unfortunate, so we postpone importing the module until it is needed.
- *Tested manually*

Use general/signature-handling settings in the 2nd stage

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autopost.rb
src/modules/AutoInstall.rb
src/modules/AutoinstGeneral.rb
test/AutoinstGeneral_test.rb

`general/signature-handling` settings are ignored in the 2nd stage.
- https://bugzilla.suse.com/show_bug.cgi?id=1197655
- https://trello.com/c/iQWIXNnG/
**WIP: I will change the code to avoid this problem in the future again**
The [AutoinstGeneral](https://github.com/yast/yast-autoinstallation/blob/81f27da576fb263ae884d0a7835331753e8552b3/src/modules/AutoinstGeneral.rb#L461-L469) module reads the profile once is imported. That's quite unfortunate, so we postpone importing the module until it is needed.

Use general/signature-handling settings in the 2nd stage (SP4)

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/rules.rnc
src/lib/autoinstall/y2erb.rb

* AutoYaST searches for "serial" and "size" disk properties in the
wrong location. It should use `/sys/block/DEVNAME` instead of `/sys/block/DEVNAME/device`.
- https://bugzilla.suse.com/1199000
* Validation of rules, when using dialogs, does not work as expected.
- https://bugzilla.suse.com/1199165
Just fix the path to the right files and update the rules syntax.

Fix disks helper and rules syntax

---

src/autoyast-rnc/rules.rnc

The fix in #836 introduces another problem in the rules syntax. Actually, the solution was easier than the one I implemented. This PR solves this issue.
Let's see a few examples of *valid* and *not valid* definitions.
<details>
<summary>Just a <dialog> element (and no conflicts list), without any other matcher is VALID</summary>
```xml
<rule>
<dialog>
<title>Desktop selection</title>
<question>GNOME</question>
<element t="integer">0</element>
</dialog>
<result>
<profile>gnome.xml</profile>
</result>
</rule>
```
</details>
<details>
<summary>A matcher (e.g., disksize)and a <dialog> element is VALID</summary>
```xml
<rule>
<disksize>
<match>/dev/sdb 20000</match>
<match_type>greater</match_type>
</disksize>
<dialog>
<title>Desktop selection</title>
<question>GNOME</question>
<element …
```

Allow only one dialog element in rules

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autoinit.rb
test/lib/clients/inst_autoinit_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1200803
- The problem is that at this point there is no repository configured yet and YaST sends empty product data to the SUSEConnect library. In that case it wants to run `zypper` to fetch the missing data. But because `zypper` is not available in the inst-sys it fails. (And it would fail anyway as there is no product data yet.)
- Originally the registration step was called only when using the Online medium, this was lost during the refactoring: https://github.com/yast/yast-autoinstallation/pull/797/files#diff-4ad40bad87181af3dfd6624224aa3eba6ab369995c2056ca64ac9ae509a9d93dL97
- Just revert that behavior and run the registration step early only when using the Online medium
- On the Online medium the product data is read from the `control.xml` …

SLE Micro registration fix

---

package/autoyast2.changes
package/autoyast2.spec
scripts/autoyast-initscripts.service

In order to prevent a ssh timeout produced because of systemd logind we [had to remove](https://github.com/yast/yast-autoinstallation/pull/824) from the initscripts service the condition to be run before systemd-user-sessions but once syste systemd logind has been patched (see https://github.com/systemd/systemd/pull/23936 & https://build.suse.de/request/show/276157) our fix can be reverted adding back the Before condition.
- https://bugzilla.suse.com/show_bug.cgi?id=1200780 & https://bugzilla.suse.com/show_bug.cgi?id=1195059
Bring back the initscripts service **Before=systemd-user-sessions** condition once systemd logind has been patched to prevent the ssh timeout.
see also https://github.com/yast/yast-installation/pull/1053

Before user sessions

---

package/autoyast2.changes
package/autoyast2.spec
scripts/autoyast-initscripts.service

It merges #842 into SLE-15-SP4 (see also https://github.com/yast/yast-installation/pull/1054)
It also depends on this systemd SR (https://build.suse.de/request/show/276156)

AutoYaST initscripts: bring back the Before=systemd-user-sessions dependency (SLE-15-SP4)

---

package/autoyast2.changes
package/autoyast2.spec
scripts/autoyast-initscripts.service

It merges https://github.com/yast/yast-autoinstallation/pull/842 into 'master' (see also https://github.com/yast/yast-installation/pull/1055)
It also depends on this systemd SR (https://build.suse.de/request/show/276156)

AutoYaST initscripts: bring back the Before=systemd-user-sessions dependency (master) 

---

package/autoyast2.changes
package/autoyast2.spec
src/clients/inst_autopost.rb

The <ask-list/> section is processed before the general section has been imported. The problem was introduced in #834.
Move the `askDialog` method to the correct place.

bsc#1201953: process <ask-list/> one the general section has been improved

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup.rb
test/lib/clients/inst_autosetup_test.rb

We are only checking needed packages for the selected backend when it is NetworkManager but not in case of wicked or netconfig.
- [bsc#1201435](https://bugzilla.suse.com/show_bug.cgi?id=1201435)
Added needed packages for the selected backend to ensure them are installed even if not declared in the software section
- Added a new unit test

Ay needed packages

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup.rb
test/lib/clients/inst_autosetup_test.rb

It merges #853 in master
- Depends on https://github.com/yast/yast-network/pull/1313

Adds the AY needed packages for the selected network backend (master)

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstConfig.rb
src/modules/ProfileLocation.rb

- https://trello.com/c/CAytlL3W
- https://jira.suse.com/browse/SLE-22578
- https://jira.suse.com/browse/SLE-24584
Add the new `repo` scheme - it needs to be treated similar to `relurl`.
For `relurl`, `file`, and `repo` URL schemes the tokenization is reworked - but is not synced with the stored tokens. This discrepancy leads to issues in `Yast::Transfer::FileFromUrl.get_file_from_url` in some cases.
Remove `label` URL scheme handling. It's now handled in [Yast::Transfer::FileFromUrl](https://github.com/yast/yast-installation/pull/1063) directly.
- https://github.com/openSUSE/linuxrc/pull/299
- https://github.com/yast/yast-installation/pull/1063
- https://github.com/yast/yast-yast2/pull/1276

fix profile location parsing and add 'repo' URL scheme

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/autoinst_profile/ask_section.rb
src/lib/autoinstall/autoinst_profile/ask_selection_entry.rb

[bsc#1204448](https://bugzilla.suse.com/show_bug.cgi?id=1204448)
Specifying empty values in the `<ask>/>` section is impossible.
https://github.com/yast/yast-yast2/pull/1170 introduced the `allow_blank` option, so now we can properly handle this case.
- *Tested manually*

bsc#1204448: allow empty values for some <ask> elements

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/autosetup_helpers.rb
src/lib/autoinstall/clients/inst_autosetup.rb
test/lib/autosetup_helpers_test.rb
test/lib/clients/inst_autosetup_test.rb

Related to https://github.com/yast/yast-security/pull/128.
* Add support to check security policies in AutoYaST.
* If displays a Y2Issue for each failing rule with `:warn` severity.
```xml
<security>
<security_policy>
<action>remediate</action> 
<policy>stig</policy>
</security_policy>
</security>
```

Add support for security policies

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup.rb
test/lib/clients/inst_autosetup_test.rb

When kdump section is not defined and product have by default then required packages are not installed.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1204180
Call always import to ensure that product default is used.
- *Added a new unit test*
- *Tested manually*
During manual testing this issue occur, but it is not related to changed code:

Fix kdump software

---

package/autoyast2.changes
package/autoyast2.spec
test/AutoInstallRules_test.rb
test/lib/autosetup_helpers_test.rb
test/lib/clients/ayast_setup_test.rb

- https://bugzilla.opensuse.org/show_bug.cgi?id=1204871 "- [Staging] rubygem-rspec-* 3.12 breaks various yast modules build"
- see https://github.com/yast/yast-yast2/pull/1279 for details

Fix hash vs keyword arguments in RSpec expectations (bsc#1204871)

---

doc/profile_conversions.md
package/autoyast2.changes
package/autoyast2.spec
xslt/new_types.xslt
xslt/old_types.xslt

If you use a new data types in the XML profile like
```xml
<confirm t="boolean">true</confirm>
```
then such profile does not work in SLE15-SP2 and older. It would be nice to provide some tools for automatic conversion to the old format which would convert it to
```xml
<confirm config:type="boolean">true</confirm>
```
- Provide XSL files for converting the profile
- See more details in the new `profile_conversions.md` document
Although the XSLT conversion should work fine in most cases there is a small problem with the CDATA sections - they are not kept and the data are converted to a string literal (with proper escaping when needed). So the conversion is not exactly 1:1, converting back to the original data types results in losing the CDATA sections (although semantically it is the very …

Add XSL files for converting between the new and old profile types.

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstSoftware.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1211154
- The product packages (`*-release`) are not installed by AutoYaST
- It turned out that the AutoYaST only restores the selected packages and patterns after calling `Pkg.PkgApplReset`
- The original idea was to extend the [PackagesProposal](https://github.com/yast/yast-yast2/blob/master/library/general/src/modules/PackagesProposal.rb) module to also handle products (in addition to patterns and packages)
- But that turned out to be very complex, we would need to update at least 5 packages (6 if we count Agama as well)
- This could also affect manual installation or upgrade and the testing would be quite difficult
- Just remember *all* selected products and restore them later (not just the base product as it was already done)
- This code …

Properly install the selected products (bsc#1202234)

---

package/autoyast2.changes
package/autoyast2.spec

master has two commits in 4.6.X, but both are already backported to SP5.
Just bump version to avoid confusion and collision.

backport SP6

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/partitioning.rnc

https://github.com/yast/yast-storage-ng/pull/1355 implements several improvements related to LUKS in AutoYaST. But adding support in the yast2-storage-ng code is not enough, the new elements also need to be added to the AutoYaST schema or they will not be accepted as part of an AutoYaST profile.
This adds the new four elements to the schema.

New LUKS-related elements in the schema of the <partition> section

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstFunctions.rb

- The HPC product (+ the HPC module) will be replaced by plain SLES + HPC module in SP6
- https://jira.suse.com/browse/PED-7841
- When the AutoYaST XML profile requests installing the `SLE_HPC` then it would display an error:
Note: The HPC product is still defined in the latest ISO. For testing I used a manually tweaked installation repository with removed `/Product-HPC` directory and updated `/media.1/products` file.
- If this change was in SLE15 -> SLE16 (or SLE12 -> SLE15) I'd avoid adding hacks to YaST and prefer to solve that on the documentation level and in the release notes.
- On the other hand  we should not break the SP6 installations with profiles that worked fine in SP5 and earlier. That would be a nasty surprise for the users. 
- This allows using the same AY profile for both …

[SLE15-SP6] Install plain SLES instead of SLE_HPC (jsc#PED-7841)

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstStorage.rb

See https://github.com/yast/yast-storage-ng/pull/1365
should be merged after the above one.
This change makes following snipped working (sets lvm_vg_reuse in created proposal(s) accordingly):
```
<general>
<storage>
<proposal>
<lvm_vg_reuse config:type="boolean">false</lvm_vg_reuse>
</proposal>
</storage>
</general>
```
- *Tested manually*

Minor tweak to allow access to lvm_vg_reuse proposal via an AY profile

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/AutoinstFunctions.rb
src/modules/AutoinstStorage.rb

[master] Install plain SLES instead of SLE_HPC (jsc#PED-7841)

---

package/autoyast2.changes
package/autoyast2.spec
src/autoyast-rnc/partitioning.rnc
src/include/autoinstall/xml.rb

Add partitioning pervasive encryption fields to the schema (see https://github.com/yast/yast-storage-ng/pull/1402)
- https://trello.com/c/Ffc1JCwe

Added pervasive encryption fields

---

package/autoyast2.changes
package/autoyast2.spec
src/modules/ProfileLocation.rb
test/ProfileLocation_test.rb

If the environment variable `YAST_SKIP_PROFILE_FETCH_ERROR` is set to "1", the error is skipped.
Agama tries to fetch the profiles from predefined locations if no URL is given. See https://github.com/agama-project/agama/pull/2180 for further details.
The problem is that, when the profile does not exist, the AutoYaST code reports an error and it should not do it because it is expected to search for those profiles silently.
Allow to disable the error by setting the environment variable `YAST_SKIP_PROFILE_FETCH_ERROR`.
- Added a new unit test

Allow skipping profile fetch errors

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup.rb

An unattended installation with a minimal profile and without a confirmation dialog does not select the security default settings and the required packages.
- https://bugzilla.suse.com/show_bug.cgi?id=1231490
- https://trello.com/c/AV5gwC6i/3970-already-late-1231490-selinux-packages-in-autoyast
Instantiate the default security settings before importing the profile to ensure them are set even without a security section or without running the confirmation dialog.
Tested manually the scenarios described below with:
**Tumbleweed:**
- **Without confirmation dialog**
- **With confirmation dialog**
**SLE-15-SP7:**
- **Without confirmation dialog**
- **With confirmation dialog**

Instantiate the default security settings before importing the profile (bsc#1231490)

---

package/autoyast2.changes
package/autoyast2.spec
src/lib/autoinstall/clients/inst_autosetup.rb

In #883 we instantiated the security settings before importing the profile to ensure the package selection was done before software was run but the firewall is still called later. 
As the SecuritySettings reads already the defaults for firewall it adds the firewalld package to the list of resolvables but if the firewall is disabled (follows the same logic that in the confirm dialog) it does not remove the package because PkgSolve is not called at all.
- https://bugzilla.suse.com/show_bug.cgi?id=1243185
Move the firewall configuration after security and before software to ensure the package selection is done according to the user preferences or defaults.
The clients or setup that is run after sotware will face the same problem that exposed by security and firewalld. For example there is …

Move the firewall configuration between security and sotware in inst_autosetup (bsc#1243185).
